#!/usr/bin/env python3
"""Build films/berserk.json - THE GOLDEN AGE, a narrated summary of Berserk season 1.

Run:  python films/build_berserk.py

Written as a builder rather than raw JSON because a 20-minute film is ~120 shots and the
shot list needs to stay readable and editable. Everything the pipeline understands is
documented in FILMCRAFT.md and craft/.

Design decisions, all deliberate:

* CHARACTER CONSISTENCY - every shot with a person carries `ref`, so the keyframe is
  generated by Qwen-Image-Edit 2511 conditioned on that character's canonical sheet. The
  face is never re-invented from words. See craft/CINEMATOGRAPHY.md section 8.
* ACTION IS CHAINED - fights use `chain: 3-4` with per-link `motion2/3/4`, giving 24-32s
  continuous takes with real choreography instead of 4s of averaged flailing.
* THE STORY IS THE FRIENDSHIP - the arc is Guts and Griffith, so the beats that get room
  are the two duels, the campfire, the overheard sentence, and the departure. Battles are
  spectacle in service of that, and the political plot is carried by narration.
* CONTENT - this is a summary of a famously brutal work. Violence is staged in silhouette
  and aftermath. The Eclipse is handled by implication: the horror is on Guts' face and in
  what the narration will not say. No sexual violence is depicted or described.
* RIGHTS - original narration and dialogue, and character designs described in our own
  terms rather than reproduced. Names are used as any summary would.
"""
import collections, json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "berserk.json")

BASE = ("dark gritty seinen anime illustration, heavy ink shadow, high contrast, muted "
        "desaturated palette, painterly, grim medieval, epic widescreen composition")
STYLE = collections.OrderedDict([
    ("default", BASE),
    ("cold",    BASE + ", flat grey overcast light, desaturated to near monochrome, no warm light"),
    ("fire",    BASE + ", firelight from below, deep orange and black, heavy chiaroscuro"),
    ("dawn",    BASE + ", pale cold dawn light, thin mist, restrained colour"),
    ("eclipse", BASE + ", crushed blacks and blood red, a black sun, hellish, near abstract"),
])

CHARS = collections.OrderedDict([
    ("GUTS", "the young black-haired swordsman from the reference image"),
    ("GRIFFITH", "the white-haired young commander in white armour from the reference image"),
    ("CASCA", "the short-haired woman soldier with deep brown skin from the reference image"),
    ("JUDEAU", "the friendly light-haired man with throwing knives from the reference image"),
    ("ZODD", "the enormous red-brown horned beast from the reference image"),
])

SHEETS = {"GUTS": "sheet_guts.png", "GRIFFITH": "sheet_griffith.png",
          "CASCA": "sheet_casca.png", "JUDEAU": "sheet_judeau.png",
          "ZODD": "sheet_zodd.png"}

VOICES = {
    # cast by timbre, not cloned from anyone. Chatterbox ships one voice; pitch, tempo and
    # a light EQ give each character a distinct read.
    "NARRATOR": {"exaggeration": 0.30, "cfg_weight": 0.35, "temperature": 0.6,
                 "pitch": 0.86, "rate": 0.86},
    "GUTS":     {"exaggeration": 0.55, "cfg_weight": 0.35, "temperature": 0.7,
                 "pitch": 0.70, "rate": 0.92,
                 "filter": "lowpass=f=7200,acompressor=threshold=-18dB:ratio=4"},
    "GRIFFITH": {"exaggeration": 0.30, "cfg_weight": 0.30, "temperature": 0.62,
                 "pitch": 1.06, "rate": 0.84},
    "CASCA":    {"exaggeration": 0.60, "cfg_weight": 0.38, "temperature": 0.78,
                 "pitch": 1.20, "rate": 0.98},
    "ZODD":     {"exaggeration": 0.70, "cfg_weight": 0.30, "temperature": 0.8,
                 "pitch": 0.55, "rate": 0.80,
                 "filter": "lowpass=f=3000,aecho=0.8:0.85:60:0.35"},
}

S = []


def sh(sid, prompt, motion, say=None, who=None, ref=None, sfx=None, look=None,
       seconds=None, chain=None, motions=None, tin=None, in_dur=None, titles=None,
       from_prev=False, quality=False, seed=None):
    d = collections.OrderedDict(id=sid)
    if tin:
        d["in"] = tin
    if in_dur:
        d["in_dur"] = in_dur
    if look:
        d["look"] = look
    if ref:
        d["ref"] = ref
    if chain:
        d["chain"] = chain
    if seconds:
        d["seconds"] = seconds
    if from_prev:
        d["from_prev"] = True
    if quality:
        d["quality"] = True
    if seed:
        d["seed"] = seed
    d["prompt"] = prompt
    d["motion"] = motion
    for i, m in enumerate(motions or [], start=2):
        d[f"motion{i}"] = m
    if say:
        d["say"] = say
        if who:
            d["who"] = who
    if sfx:
        d["sfx"] = sfx
    if titles:
        d["titles"] = titles
    S.append(d)


# ══════════════════════════════════════════════════════ ACT I — THE MERCENARY
sh("010_field",
   "Extreme wide shot of a medieval battlefield at first light, hundreds of dead men and horses in churned mud, broken spears standing like reeds, smoke lying flat across the ground, one small armoured figure standing alone at the centre of it",
   "Smoke drifts across the mud. Crows lift off the bodies. The lone figure does not move. Very slow push in.",
   say="A man is found standing in a field of the dead. He is not the victor. He is only the one still standing.",
   look="cold", sfx="A cold dawn wind over a battlefield, crows, distant timber settling, no voices",
   titles=[{"text": "BERSERK", "at": 1.4, "hold": 3.6, "scale": 0.062, "y": 0.42},
           {"text": "the golden age", "at": 2.1, "hold": 3.0, "scale": 0.026, "y": 0.56}])

sh("020_guts_face",
   "Extreme close-up of the face of {GUTS}, spattered with mud and blood, breathing hard, eyes flat and empty, a small scar across the bridge of his nose",
   "His chest rises and falls hard. Blood runs from his hairline past one eye. He blinks once, slowly. Nothing behind the eyes.",
   say="His name is Guts. He was born on a battlefield and raised by the man who found him there.",
   ref=["GUTS"], look="cold", tin="cut",
   sfx="Heavy ragged breathing, blood dripping onto steel, wind")

sh("030_child",
   "Wide shot of a mercenary camp at night seen from a child's low vantage, rough men drinking around fires, tents and stacked weapons, a very small boy of about nine holding a sword far too big for him at the edge of the firelight",
   "The men laugh and drink around the fires. The small boy stands at the edge, both hands on the huge hilt. Firelight moves across him. He does not join them.",
   say="He was given a sword before he was given a reason. By nine he had killed a man. By eleven he was alone.",
   look="fire", tin="dissolve",
   sfx="A rowdy mercenary camp at night, fires crackling, tankards, coarse laughter kept low and indistinct")

sh("040_sell",
   "Harsh shot inside a dim tent of a hard-faced mercenary captain taking coins from another man's hand, a small boy visible out of focus behind them sitting on a cot, one lamp, deep shadow",
   "Coins pass from hand to hand and are closed in a fist. The lamp flame gutters. Neither man looks toward the boy behind them.",
   say="The man who raised him sold him for three silver coins, and later tried to kill him. Guts killed him instead, and walked out of the only life he had.",
   look="fire", tin="cut",
   sfx="Coins counted into a palm, a lamp guttering, canvas shifting, low murmur")

sh("050_merc_years",
   "Montage-style wide shot of a lone swordsman crossing a bleak landscape of burnt farms and gallows under a grey sky, carrying an enormous sword across his back, small in a wide frame",
   "He walks steadily away from camera across the frame. Wind pulls at his cloak. Rain begins. He does not slow.",
   say="For years he sold the only thing he had. He fought for whoever paid, and he did not lose.",
   ref=["GUTS"], look="cold", tin="dissolve",
   sfx="Wind across open country, rain beginning, footsteps in mud, a distant rope creaking")

# --- the Bazuso fight: chained set-piece -------------------------------------
sh("060_siege",
   "Epic wide shot of a medieval siege at dusk, a stone fortress wall with ladders against it, hundreds of soldiers surging forward with torches and spears, arrows in the air, smoke and fire",
   "The mass of soldiers surges up the ladders. Arrows arc overhead. Fire climbs the wall. Chaotic, huge, kinetic.",
   say="At the siege of a fortress whose name no one remembers, a giant held the breach.",
   look="fire", tin="dissolve", seconds=6,
   sfx="A full medieval siege, hundreds of men shouting, ladders slamming stone, arrows, fire roaring")

sh("070_bazuso",
   "Low angle of an enormous armoured knight standing in a breached gateway, a head and shoulders taller than the men around him, full plate and a huge double-headed axe, dead soldiers heaped at his feet, torchlight",
   "The giant knight lifts the axe onto his shoulder and roars. The men in front of him back away. Torch smoke rolls past.",
   say="He had killed everyone sent at him. The men had stopped being sent.",
   look="fire", tin="cut", seconds=5,
   sfx="A huge man roaring inside a stone gateway, armour, frightened soldiers backing off, fire")

sh("080_charge",
   "Dynamic low shot of {GUTS} walking out of the ranks alone toward the breach, the enormous sword dragging point-down behind him and throwing sparks off the flagstones, soldiers parting on both sides, firelight",
   "He walks forward alone, the huge blade dragging and sparking on the stone behind him. The ranks part. He does not stop or look up.",
   motions=["He breaks into a run and swings the great sword up in both hands as the giant's axe comes down; the two weapons meet and the shock throws sparks and dust outward",
            "The giant's return blow catches him and hurls him bodily through a burning market stall; he rolls through the wreckage, comes up on one knee, and spits blood",
            "He drives up from underneath, both hands on the hilt, and the enormous blade goes through the giant's guard; the huge armoured body folds and comes down"],
   say="One mercenary walked out of the line.",
   ref=["GUTS"], look="fire", tin="cut", chain=4, seconds=30,
   sfx="A colossal sword dragging on stone throwing sparks, then two heavy blades meeting with a shattering clang, timber breaking, a huge body falling")

sh("090_aftermath",
   "Wide shot of {GUTS} standing over the enormous armoured corpse in the ruined gateway, sword resting on the stone, hundreds of soldiers staring at him in complete silence, firelight and drifting ash",
   "Ash drifts down through the firelight. The soldiers stare without a sound. He stands still, breathing hard, and does not acknowledge any of them.",
   say="The army had a story to tell for the rest of their lives. Guts collected his pay.",
   ref=["GUTS"], look="fire", tin="dissolve", seconds=6,
   sfx="Sudden silence after a battle, fire crackling, ash falling, one man's heavy breathing")

sh("100_griffith_watch",
   "Striking shot of {GRIFFITH} on horseback on a rise above the burning fortress, white armour catching the firelight, perfectly still, watching, a banner of mercenaries behind him in silhouette",
   "His cloak lifts in the heat rising off the fortress. His horse shifts under him. He watches without moving. Firelight plays across the white armour.",
   say="Someone else had been watching too.",
   ref=["GRIFFITH"], look="fire", tin="cut", seconds=5,
   sfx="Wind over a hill, horses shifting and snorting, distant fire, banners in wind")

sh("110_griffith_intro",
   "Medium shot of {GRIFFITH} in white armour standing in a mercenary camp at dusk, calm and composed, men working behind him, a hawk banner on a pole",
   "He turns his head toward camera. The banner snaps in the wind behind him. His expression does not change. Utterly composed.",
   say="Griffith. Commander of a mercenary band called the Band of the Hawk, and the most dangerous man Guts would ever meet.",
   ref=["GRIFFITH"], look="dawn", tin="dissolve",
   sfx="A busy camp at dusk, banners in wind, horses, armour, low voices")

# --- first duel: Griffith wins ----------------------------------------------
sh("120_duel1_setup",
   "Wide two-shot at dusk on open ground outside a camp, {GUTS} on the left with the enormous sword raised and {GRIFFITH} on the right with a slender longsword held low, mercenaries watching in a loose ring around them",
   "Both men settle into stance. The watching ring goes quiet. Wind moves the grass between them. Neither moves first.",
   say="Griffith wanted him. Guts told him what he could do with the offer.",
   ref=["GUTS", "GRIFFITH"], look="dawn", tin="dissolve", seconds=6,
   sfx="Wind across open ground, a ring of men falling quiet, leather and steel settling")

sh("130_duel1",
   "Dynamic action shot of {GUTS} swinging the enormous sword down at {GRIFFITH}, who is already moving inside the arc, the huge blade passing through empty air, dust kicked up between them, dusk light",
   "Guts brings the huge blade down hard. Griffith slips inside the arc before it lands. The sword hits earth and throws up dust.",
   motions=["Guts recovers and swings again wider; Griffith turns the blow aside with the flat of his slender sword and lets the weight carry Guts past him",
            "Griffith steps in behind the swing, hooks a foot and puts Guts face down in the dirt with the point of the longsword at the back of his neck"],
   ref=["GUTS", "GRIFFITH"], look="dawn", tin="cut", chain=3, seconds=22,
   sfx="Heavy blade cutting air and striking earth, fast light footwork, a body hitting the ground hard, a sword point ringing")

sh("140_duel1_end",
   "Close two-shot of {GUTS} face down in the dirt with {GRIFFITH} standing over him, sword point at his neck, Griffith's expression calm rather than triumphant, dust settling around them",
   "Dust settles. Guts' hand closes uselessly in the dirt. Griffith looks down at him without any satisfaction at all.",
   say="From now on, you belong to me.",
   who="GRIFFITH",
   ref=["GUTS", "GRIFFITH"], look="dawn", tin="cut",
   sfx="Dust settling, one man breathing hard into the dirt, a blade held perfectly still")

sh("150_guts_owned",
   "Close-up of the face of {GUTS} in the dirt, cheek against the ground, teeth bared in fury and humiliation, eyes burning",
   "His jaw works. He drags in a breath through his teeth. His eyes stay locked forward, furious, refusing to look up.",
   say="He had been sold once before. He knew exactly what the words meant.",
   ref=["GUTS"], look="dawn", tin="cut",
   sfx="Ragged furious breathing against dirt, distant camp noise")

# ══════════════════════════════════════════════════════ ACT II — THE HAWKS
sh("200_hawks_ride",
   "Magnificent wide shot of a mercenary company riding in column across open country at dawn, a hawk banner at the head, five hundred riders and wagons stretching back, mist lying in the low ground",
   "The column rides steadily across frame. The banner leads. Mist parts around the horses. Long, sweeping, majestic camera move alongside them.",
   say="The Band of the Hawk. Five hundred men who had chosen one man's dream over their own.",
   look="dawn", tin="fade", in_dur=1.6, seconds=7,
   sfx="A large mounted column on the move, hundreds of hooves, wagon wheels, harness, banners")

sh("210_judeau",
   "Warm medium shot of {JUDEAU} sitting on a supply wagon cleaning a throwing knife, half smiling, other soldiers around him at rest, afternoon light",
   "He turns the knife over, tests the edge with his thumb, and glances up with an easy half smile. The wagon rocks under him.",
   say="Judeau, who could put a knife through a coin at forty paces, and who noticed everything about everyone.",
   ref=["JUDEAU"], tin="dissolve",
   sfx="A wagon on the move, a whetstone on a blade, relaxed camp sounds")

sh("220_casca_intro",
   "Medium shot of {CASCA} in the saddle in half armour, reining her horse around to face camera, hard and unimpressed, the column moving behind her",
   "She turns the horse sharply and levels a flat unfriendly stare at camera. Her cloak swings. The horse tosses its head.",
   say="Casca. The only woman in the company, and the only one who had earned her place twice over to keep it.",
   ref=["CASCA"], tin="cut",
   sfx="A horse reined around hard, harness, hooves on packed earth")

sh("230_casca_hates",
   "Tense two-shot in camp of {CASCA} squared up close to {GUTS}, jabbing a finger at his chest, furious, other soldiers watching from a distance, evening light",
   "She jabs a finger hard into his chest plate and holds it there, saying something short. He looks down at her without moving at all.",
   say="You are a mad dog he picked up. That is all you will ever be.",
   who="CASCA",
   ref=["CASCA", "GUTS"], tin="cut",
   sfx="Two people squared up close, armour, a sharp jab against a breastplate, camp noise beyond")

sh("240_battles",
   "Epic wide battle shot of the Band of the Hawk charging into an enemy line on open ground, the hawk banner at the centre, horses and infantry colliding, spears breaking, dust and blood spray in silhouette",
   "The two lines collide in the centre of frame. Spears break. Horses go down. Dust boils up and swallows the middle distance. Violent and huge.",
   motions=["The Hawk line breaks through and turns; the enemy formation buckles inward and begins to come apart",
            "Riders pour through the gap into the enemy rear as the banner is carried forward over the wreck of the line"],
   say="For three years they won. Not because they were stronger, but because Griffith saw the shape of a battle the way other men see a room.",
   look="cold", tin="dissolve", chain=3, seconds=24,
   sfx="Two armies colliding, hundreds of men and horses, spears splintering, a war horn, chaos")

sh("250_guts_fights",
   "Brutal action shot of {GUTS} mid-swing in a press of enemy soldiers, the enormous sword clearing an arc around him, men thrown back, seen slightly in silhouette against dust and low sun",
   "The huge blade comes round in a full arc and clears the space around him. Men are thrown back out of frame. He is already turning into the next swing.",
   motions=["He drives forward through the gap he has made, shoulder down, and cuts a second arc that empties the ground ahead of him",
            "A spear takes him across the ribs; he tears it out of the man's hands, breaks it, and keeps going"],
   say="And because Guts, put at the point of any attack, went through it.",
   ref=["GUTS"], look="cold", tin="cut", chain=3, seconds=22,
   sfx="A huge blade clearing an arc, bodies thrown, a spear shaft snapping, close brutal combat")

sh("260_campfire",
   "Intimate two-shot at a campfire at night, {GRIFFITH} sitting with his arms on his knees and {GUTS} across the fire from him, firelight on both faces, the camp asleep in the darkness beyond",
   "The fire moves between them. Griffith turns a stick in the embers. Guts watches him. Neither of them is in any hurry.",
   say="They talked at night, when the camp was asleep. It became the only hour of the day either of them told the truth in.",
   ref=["GRIFFITH", "GUTS"], look="fire", tin="fade", in_dur=1.4, seconds=7,
   sfx="A small fire at night, embers shifting, a sleeping camp, insects, quiet")

sh("270_dream",
   "Close-up of {GRIFFITH} lit from below by the campfire, looking into the flames rather than at his companion, calm and absolutely certain",
   "Firelight moves across his face. He does not look up. His expression is completely untroubled by the size of what he is saying.",
   say="I want a kingdom of my own. Not given to me. Taken, and held, and mine.",
   who="GRIFFITH",
   ref=["GRIFFITH"], look="fire", tin="cut",
   sfx="A fire close by, one voice speaking quietly, a sleeping camp beyond")

sh("280_guts_listens",
   "Close-up of {GUTS} across the fire, listening, firelight on one side of his face, an expression he does not have a name for",
   "He watches the other man steadily. Something moves behind his eyes and he looks away into the dark, then back.",
   say="Guts had never wanted anything. It had never occurred to him that a man was allowed to.",
   ref=["GUTS"], look="fire", tin="cut",
   sfx="A fire, one man shifting his weight, night insects")

sh("290_price",
   "Wide shot of the campfire from outside the circle of light, the two small figures facing each other across it, the enormous dark of the camp and the hills all around them",
   "The fire burns low between the two seated figures. The dark presses in around the small ring of light. Very slow drift backward.",
   say="He also said what such a kingdom would cost. Guts heard it as loyalty. It was a warning.",
   look="fire", tin="dissolve", seconds=6,
   sfx="A fire heard from a distance, wide open night, wind, a horse somewhere")

sh("300_casca_story",
   "Flashback-style shot in cold blue light of a young girl in a torn dress on the ground in a forest and a white-armoured youth on horseback above her, holding a sword down to her hilt-first",
   "The mounted figure leans down and offers the sword hilt-first. The girl on the ground stares up at it. Rain drips through the branches.",
   say="Casca had been a farm girl sold to a nobleman. Griffith put a sword in her hands instead and told her to decide her own life. She had followed him ever since.",
   look="cold", tin="dissolve", seconds=7,
   sfx="Rain in a forest, a horse breathing, a sword offered, cold quiet")

sh("310_cliff",
   "Dramatic wide shot of {GUTS} and {CASCA} falling down a steep wet rock face together in the rain, both grabbing at nothing, a river far below",
   "The two figures slide and tumble down the wet rock, grabbing at each other and at the stone. Rain hammers. They vanish into the dark below.",
   ref=["GUTS", "CASCA"], look="cold", tin="cut", seconds=5,
   sfx="Two bodies sliding down wet rock, hammering rain, scree falling, a river below")

sh("320_cave",
   "Intimate shot in a small cave lit by a tiny fire, {CASCA} shivering wrapped in a wet cloak and {GUTS} sitting apart from her against the rock, rain sheeting past the entrance",
   "The little fire struggles. She shivers hard and pulls the cloak tighter. He watches the rain rather than her. Neither speaks for a long moment.",
   say="They spent that night not killing each other, which was new for both of them.",
   ref=["CASCA", "GUTS"], look="fire", tin="dissolve", seconds=7,
   sfx="Rain outside a cave mouth, a small struggling fire, someone shivering, dripping water")

sh("330_casca_truth",
   "Close-up of {CASCA} in firelight, wet hair against her face, looking at something out of frame, her hard expression open for once",
   "She looks up, and for the first time her face is not armoured. Firelight catches the water on her skin. She almost smiles, and doesn't.",
   say="He is the only reason I am not somebody's property. I would burn the world down for him. So would you, if you understood him at all.",
   who="CASCA",
   ref=["CASCA"], look="fire", tin="cut",
   sfx="A small fire, rain outside, a quiet voice, cloth shifting")

sh("340_rise",
   "Grand wide shot of a royal capital at dawn, white towers and banners above a walled city, a mercenary column riding in through the main gate with crowds along the walls",
   "The column rides in under the gate. Crowds wave from the walls. Banners lift. Bells begin. Bright and triumphant.",
   say="Three years of victories bought Griffith what no mercenary had ever been given. A title, a command, and a place at court.",
   look="dawn", tin="fade", in_dur=1.4, seconds=7,
   sfx="A city gate at dawn, cheering crowds, bells, a mounted column entering, banners")

sh("350_court",
   "Wide shot of a candlelit throne room, {GRIFFITH} kneeling before a seated king on a dais, courtiers and nobles in rich clothes watching from both sides, cold formal light",
   "Griffith kneels and lowers his head. The nobles watch him with open hostility. Candle flames stand still in the airless hall.",
   say="The nobility understood immediately what he was. A commoner with an army who had been let inside the walls.",
   ref=["GRIFFITH"], tin="dissolve", seconds=6,
   sfx="A large formal hall, courtly murmuring, armour kneeling on marble, candles")

# --- Zodd -------------------------------------------------------------------
sh("400_zodd_reveal",
   "Terrifying low angle of {ZODD} standing in a ruined stone hall, horns almost touching the broken ceiling, dead soldiers strewn around its feet, moonlight through the shattered roof",
   "The beast turns its head slowly toward camera and its eyes catch the moonlight. It rolls its shoulders. Dust falls from the broken roof above.",
   say="Then they met something that should not have existed.",
   ref=["ZODD"], look="cold", tin="fade", in_dur=1.6, seconds=6,
   sfx="Something enormous moving in a stone hall, claws on flagstone, a deep inhuman breath, falling dust")

sh("410_zodd_fight",
   "Explosive action shot of {ZODD} smashing through a stone pillar to reach {GUTS}, the huge beast mid-lunge, Guts bringing the enormous sword across to meet it, debris exploding outward",
   "The beast smashes through the pillar and lunges. Guts brings the great sword across into it. The impact throws both of them and a wall of debris outward.",
   motions=["Guts is hurled the length of the hall into a wall; he comes up out of the rubble and charges straight back at it",
            "{GRIFFITH} comes in from the beast's flank, fast and precise, and opens a line across its ribs, and the two men fight it together",
            "The beast catches Guts and drives him down through a stone table, then turns on Griffith as Guts drags himself up on the sword"],
   ref=["GUTS", "ZODD"], look="cold", tin="cut", chain=4, seconds=32,
   sfx="A stone pillar exploding, an enormous beast roaring, huge blades on hide, a body driven through stone, sustained violence")

sh("420_zodd_stops",
   "Tense close shot of {ZODD} halted mid-motion, its burning eyes fixed not on the swordsman but on something off frame, an expression almost like recognition on the bestial face",
   "The beast freezes completely. Its eyes track past the man in front of it to something off frame. Its lips draw back from its teeth. It stops fighting.",
   say="It stopped. Not because it was losing.",
   ref=["ZODD"], look="cold", tin="cut",
   sfx="Sudden stillness after violence, a huge creature breathing, dust settling")

sh("430_behelit",
   "Extreme macro close-up of a small egg-shaped red stone hanging at a throat, its surface marked with what look like a pair of eyes and a mouth, faintly wet, catching moonlight",
   "The marks on the stone's surface shift very slightly, as if settling into a face. A drop of moisture runs down it. It seems to breathe.",
   say="Because of something Griffith wore at his throat, and had worn since he was a boy.",
   look="cold", tin="cut",
   sfx="A tiny wet sound like something turning over, a faint held tone, unnatural quiet")

sh("440_zodd_warning",
   "Ominous shot of {ZODD} on the broken wall above, half turned away to leave, looking back down over its shoulder at the men below, moonlight along its horns",
   "It hauls itself onto the broken wall, then stops and looks back down over its shoulder. Its wings or arms flex. It says something and does not wait for an answer.",
   say="When his dream collapses, and it will, you will see something you cannot fight. Run then. If you are still alive.",
   who="ZODD",
   ref=["ZODD"], look="cold", tin="cut",
   sfx="Something huge climbing broken stone, a low inhuman voice, wind through a ruined roof")

# --- the overheard sentence: the pivot --------------------------------------
sh("500_overheard",
   "Quiet shot in a stone corridor at night, {GUTS} stopped just outside a lit doorway with his hand on the frame, listening, his face lit down one side by the light from inside",
   "He stops with one hand on the door frame. Light from the room falls across half his face. He does not go in. He listens.",
   say="He was not meant to hear it.",
   ref=["GUTS"], look="fire", tin="fade", in_dur=1.4,
   sfx="A stone corridor at night, muffled voices through a door, a hand on wood, held breath")

sh("510_griffith_friend",
   "Warm interior shot of {GRIFFITH} in a lamplit room, half turned away, speaking to someone off frame, relaxed and honest in a way he is never seen to be in public",
   "He turns a cup slowly in his hands as he speaks, looking into it rather than at whoever he is answering. Lamplight moves across him.",
   say="A friend is not someone who follows me. A friend is someone who stands beside me because he is going somewhere of his own.",
   who="GRIFFITH",
   ref=["GRIFFITH"], look="fire", tin="cut",
   sfx="A quiet lamplit room, a cup turned on a table, one voice speaking evenly")

sh("520_guts_realises",
   "Extreme close-up of the face of {GUTS} in the dark corridor, the sentence landing, his expression changing from confusion to something like grief",
   "His eyes move as the words land. His jaw tightens. He closes his eyes for a moment and something goes out of his face.",
   say="Guts had spent three years being the best sword another man owned. He had never once been Griffith's friend.",
   ref=["GUTS"], look="fire", tin="cut",
   sfx="A held breath released, muffled voices beyond a door, a corridor's stone quiet")

sh("530_decision",
   "Wide shot of {GUTS} sitting alone on a battlement at dawn with the enormous sword across his knees, the sleeping camp and the plain far below, cold pale light",
   "He sits without moving as the light comes up. Mist lifts off the plain below. His hands rest on the blade. He has already decided.",
   say="So he decided to go and find out what he wanted, so that one day he could come back and stand beside him instead of behind him.",
   ref=["GUTS"], look="dawn", tin="dissolve", seconds=7,
   sfx="A cold dawn on stone battlements, wind, a sleeping camp far below, birds beginning")

sh("540_tell_casca",
   "Two-shot at dawn of {CASCA} standing in front of {GUTS} on the battlement stair, blocking his way, furious and frightened at once",
   "She steps into his path and stays there. Her hands are shaking. He waits for her to move, and she does not.",
   say="If you go, you will break him. You are the only thing he has that he did not plan for.",
   who="CASCA",
   ref=["CASCA", "GUTS"], look="dawn", tin="cut",
   sfx="Wind on a stone stair, two people close and not touching, armour, a shaken voice")

# --- second duel: Guts wins -------------------------------------------------
sh("550_duel2",
   "Wide two-shot at dawn in a snowy courtyard, {GRIFFITH} with his slender sword drawn and {GUTS} with the enormous blade lowered, snow falling between them, the Hawks watching from the walls in silhouette",
   "Snow falls between them. Both settle. The watching figures on the walls do not move. Then Griffith attacks first, fast and precise.",
   motions=["Griffith's blade comes in three times in a heartbeat and Guts turns each one aside with the flat of the huge sword, giving ground and watching",
            "Guts steps in instead of back, takes the fourth strike on his shoulder plate and brings the great sword round in one enormous rising arc",
            "The slender sword shatters at the guard and spins away into the snow; the fragments fall; Griffith stands empty-handed and still"],
   say="Griffith wagered his command on the duel, and lost it.",
   ref=["GUTS", "GRIFFITH"], look="dawn", tin="fade", in_dur=1.6, chain=4, seconds=30,
   sfx="Snow-muffled courtyard, a fast light blade striking a heavy one three times, a huge rising swing, steel shattering, fragments in snow")

sh("560_broken_sword",
   "Macro close-up of the broken half of a slender longsword lying in fresh snow, the break bright and new, snowflakes settling on the steel",
   "Snow settles onto the broken steel. The bright break dulls as the flakes cover it. Nothing else moves.",
   look="dawn", tin="cut", seconds=4,
   sfx="Snow falling on steel, absolute muffled quiet, one distant footstep")

sh("570_guts_leaves",
   "Wide shot from behind of {GUTS} walking away down a snowy road with the enormous sword on his back, and far behind him {GRIFFITH} standing alone in the courtyard gate watching him go",
   "Guts walks steadily away from camera down the road. Behind him the small white figure in the gateway does not move at all. Snow falls between them.",
   say="He did not look back. He thought he had years.",
   ref=["GUTS"], look="dawn", tin="dissolve", seconds=8,
   sfx="Boots in fresh snow receding, wind, a gate creaking somewhere behind, emptiness")

sh("580_griffith_alone",
   "Devastating close-up of {GRIFFITH} alone in the snowy gateway, empty hands at his sides, his composure gone for the first time, snow on his white armour",
   "His hand closes slowly on nothing. Snow settles on his shoulders. His face finally breaks, and there is no one there to see it.",
   say="Griffith had never lost anything before. He did not know how to do it.",
   ref=["GRIFFITH"], look="dawn", tin="cut",
   sfx="Snow falling, one person breathing unevenly, a vast quiet courtyard")

# ══════════════════════════════════════════════════════ ACT III — THE FALL
sh("600_reckless",
   "Cold shot of a candlelit war room, {GRIFFITH} alone over a map table at night, dozens of guttering candles, his shadow thrown huge across the wall behind him",
   "He moves a marker on the map, then stops with his hand on it. The candles gutter. His shadow shifts across the wall. He does not sleep.",
   say="What he did next, he did quickly, and for reasons he would never explain to anyone.",
   ref=["GRIFFITH"], look="fire", tin="fade", in_dur=1.6, seconds=6,
   sfx="A quiet war room at night, many candles, parchment, a marker set down on wood")

sh("610_arrest",
   "Violent shot of royal guards in ornate armour seizing {GRIFFITH} in a palace corridor, four men holding him, his sword already on the floor, a triumphant noble watching from the end of the hall",
   "The guards take him from both sides and force him down. His sword rings on the marble. The noble at the end of the hall does not move closer.",
   say="The court had been waiting a long time for a reason. He handed them one.",
   ref=["GRIFFITH"], tin="cut", seconds=5,
   sfx="Armoured men seizing someone, a sword hitting marble, a struggle in a stone hall, a door slamming")

sh("620_year",
   "Bleak wide shot of an iron door at the bottom of a stone shaft, one shaft of light from far above, the floor wet, chains on the walls, no figure visible",
   "Water drips through the light from far above. The shaft of light moves slowly across the wet floor as the sun crosses. Nothing else happens.",
   say="They kept him for a year. What they did to him in that year was designed so that he could never be a threat again.",
   look="cold", tin="fade", in_dur=1.6, seconds=8,
   sfx="A deep stone shaft, water dripping, chains shifting, a door far above, terrible patience")

sh("630_hawks_hunted",
   "Wide shot of a ragged mercenary band camped in winter forest, far fewer than before, wounded men, no banner flying, snow on the tents",
   "Snow sifts down through the bare branches onto the ragged camp. A wounded man is helped past. There is no banner anywhere in frame.",
   say="The Hawks were declared traitors and hunted through two winters. Casca held them together because there was no one else left to do it.",
   look="cold", tin="dissolve", seconds=7,
   sfx="A cold thin camp in winter forest, snow, wounded men, no music, no cheer")

sh("640_guts_returns",
   "Striking shot of {GUTS} walking into the ragged winter camp, bigger than when he left, a new scar, the enormous sword on his back, the ragged soldiers turning to look at him",
   "He walks in through the trees and stops. The ragged men turn one by one. Snow falls between them. Nobody speaks.",
   say="Guts came back a year later, with an answer he never got to give.",
   ref=["GUTS"], look="cold", tin="cut", seconds=6,
   sfx="Boots in snow entering a camp, men getting to their feet, snow, silence")

sh("650_rescue",
   "Action shot of {GUTS} and {CASCA} fighting through a torchlit dungeon corridor, guards falling back before them, the enormous sword filling the corridor, torch smoke",
   "The huge blade clears the corridor ahead of them. Guards break and run. The two of them push forward through the smoke without stopping.",
   motions=["They reach a barred iron door; Guts sets the great sword against it and tears it out of the stone wall in a burst of dust",
            "They come through into the dark beyond and both stop dead in the doorway"],
   say="They went into the tower after him.",
   ref=["GUTS", "CASCA"], look="fire", tin="dissolve", chain=3, seconds=22,
   sfx="Fighting in a narrow stone corridor, guards routed, an iron door torn from stone, then abrupt silence")

sh("660_griffith_ruined",
   "Devastating shot in near darkness of a thin ruined figure in a torn shift huddled on the floor of a cell, an iron mask covering the face, limbs wasted, unable to rise, one shaft of light",
   "The figure does not react to the light or the noise. One hand lies open on the stone. The shoulders move very slightly. Nothing else.",
   say="A year had taken his voice, his hands and his legs. The man who had wanted a kingdom could not stand, and could not speak, and could not be looked at.",
   look="cold", tin="cut", seconds=8,
   sfx="A cell in near silence, one shallow breath, chains, water, the worst quiet in the film")

sh("670_carry",
   "Wrenching shot of {GUTS} carrying the ruined thin figure out of the tower in his arms down a spiral stair, the body far too light, {CASCA} ahead of them with a torch, tears on her face",
   "He carries the light body down the stair. Casca goes ahead with the torch and keeps looking back. The torchlight shakes.",
   ref=["GUTS", "CASCA"], look="fire", tin="cut", seconds=6,
   sfx="Slow heavy footsteps on a spiral stair, a torch, someone crying without sound, cloth")

sh("680_cart",
   "Bleak wide shot of a small cart on a moorland road at dusk, the ragged remnant of the band walking alongside it, the hooded ruined figure sitting in the cart, grey sky",
   "The cart rocks along the rough road. The walking figures keep pace. The hooded figure in the cart does not move with the motion, only sways.",
   say="They ran for weeks. He never spoke. Casca fed him and did not let anyone else near him.",
   look="cold", tin="dissolve", seconds=7,
   sfx="A cart on a rough moor road, wheels, walking men, wind, low grey emptiness")

sh("690_behelit_again",
   "Macro close-up of the small red egg-shaped stone lying in a thin ruined hand in the bottom of a cart, its marked surface beginning to weep, the eyes on it opening",
   "The marks on the stone rearrange themselves into a face and the eyes open. Fluid runs from them. The hand holding it does not move.",
   say="Then the stone at his throat opened its eyes.",
   look="eclipse", tin="cut", seconds=5,
   sfx="A wet unnatural sound, a rising impossible tone, everything else falling away")

# --- the Eclipse: handled by implication ------------------------------------
sh("700_eclipse",
   "Apocalyptic wide shot of a moorland turned to a plain of red flesh and standing stones under a black sun in a red sky, thousands of grotesque silhouetted shapes crowding the horizon, the small band tiny at the centre",
   "The black sun hangs motionless. The horizon crawls with shapes. The ground itself breathes. The tiny figures at the centre turn slowly, surrounded.",
   say="The world came apart, and something on the other side of it had been waiting for this exact moment for a very long time.",
   look="eclipse", tin="fade", in_dur=1.6, seconds=8,
   sfx="Reality tearing, a vast inhuman chorus, wind that is not wind, a heartbeat under everything")

sh("710_godhand",
   "Terrifying shot of four colossal inhuman figures seated in the air above the red plain, monstrous and serene, hugely out of scale, backlit by the black sun",
   "The four vast shapes settle in the air without moving their limbs. The black sun burns behind them. Everything below them is small.",
   say="They offered him what he had always wanted. They named the price.",
   look="eclipse", tin="cut", seconds=6,
   sfx="Four vast presences, a deep chorus of inhuman voices, pressure, dread beyond fear")

sh("720_choice",
   "Close shot of the ruined hooded figure kneeling on the red ground, head lifting for the first time, the black sun above, his ragged band silhouetted behind him unaware",
   "For the first time the ruined figure lifts its head. Behind it the silhouetted band stand facing outward, watching the horizon, backs turned to him.",
   say="Everyone he had. Everyone who had followed him. That was the price, and he had one moment to answer.",
   look="eclipse", tin="cut", seconds=7,
   sfx="A vast waiting silence, a chorus holding one note, a single breath drawn")

sh("730_answer",
   "Abstract shot of the black sun filling almost the whole frame, a single small kneeling silhouette at the bottom edge, red light bleeding around the black disc",
   "The black disc burns. Red light bleeds around its edge and slowly floods the frame. The small silhouette below does not move.",
   say="He said yes.",
   look="eclipse", tin="cut", seconds=5,
   sfx="One enormous tolling note, a chorus resolving into something triumphant and wrong")

sh("740_slaughter",
   "Chaotic near-abstract shot of silhouetted human figures fighting a tide of grotesque shapes on a red plain, seen from far off and half lost in the dark, no detail, only the shape of an ending",
   "The small silhouettes are surrounded and go down one by one, seen from too far away to make out. The tide closes over where they were.",
   say="What the demons did to the Band of the Hawk took a long time, and this account will not describe it.",
   look="eclipse", tin="cut", seconds=7,
   sfx="A distant overwhelming massacre kept far off and indistinct, a chorus rising over it")

sh("750_judeau",
   "Close shot in red darkness of {JUDEAU} on the ground, propped on one arm, mortally hurt, still trying to say something to someone off frame, almost calm",
   "He gets up onto one elbow, tries to speak, and cannot. He makes himself smile instead, at whoever is off frame, and then his arm gives out.",
   say="Judeau, who noticed everything, spent the last of it trying to tell Casca something kind.",
   ref=["JUDEAU"], look="eclipse", tin="cut",
   sfx="Close laboured breathing, a hand slipping on wet ground, chaos far behind")

sh("760_guts_arm",
   "Brutal near-silhouette of {GUTS} pinned under a mass of grotesque shapes, one arm trapped and being torn, his own sword driven into the ground beside him, red light",
   "The shapes swarm over the trapped arm. He wrenches his body around and gets a hand on the sword hilt. Everything is red and moving.",
   say="Guts tore his own arm free of the thing that had it, and did not stop.",
   ref=["GUTS"], look="eclipse", tin="cut", seconds=5,
   sfx="A body being crushed and fighting, a scream of rage rather than pain, wet chaos")

sh("770_guts_watches",
   "Devastating extreme close-up of the face of {GUTS} held down against the red ground, one eye ruined and blind, the other forced open, screaming at something he cannot reach",
   "He is held down and his head forced round. One eye is gone. The other is wide open. He is screaming without any sound coming out.",
   say="They held him where he could see, and made him watch, and that was the point.",
   ref=["GUTS"], look="eclipse", tin="cut",
   sfx="A throat screaming itself raw with no sound, a chorus swelling over it, everything muffling")

sh("780_brand",
   "Macro close-up of a mark being burned into skin at the base of a neck, a small brand shaped like a wound, blood running from it, red light",
   "The mark sears into the skin and blood runs from it immediately. Steam rises. The skin around it shudders.",
   say="They marked him before they let him live. A brand that bleeds, so that everything on the other side would always know where to find him.",
   look="eclipse", tin="cut", seconds=5,
   sfx="Skin searing, a wet hiss, breath forced out through teeth")

sh("790_griffith_reborn",
   "Awful beautiful shot of a figure descending through red light in the shape of a young man with white wings and long white hair, no longer human, serene and remote, the red plain far below",
   "The winged figure descends slowly through the red light without effort, hair and wings moving. Its face is calm and knows exactly what it has done.",
   say="And what came down out of that light wearing his friend's face did not look at him at all.",
   look="eclipse", tin="cut", seconds=7,
   sfx="Enormous wings in still air, a chorus of adoration, a single held terrible note")

# ══════════════════════════════════════════════════════ CODA
sh("800_after",
   "Bleak dawn wide shot of an ordinary empty moor, the standing stones gone, no red plain, ordinary grey mist and wet grass, one small figure kneeling in the middle of nothing",
   "Mist moves across ordinary wet grass. The kneeling figure is the only thing in frame. Birds begin somewhere. The world is completely normal again.",
   say="In the morning it was an empty field again. Two of them were alive.",
   look="cold", tin="fade", in_dur=1.6, seconds=8,
   sfx="An ordinary damp moor at dawn, birds beginning, wind in grass, unbearable normality")

sh("810_casca_after",
   "Quiet devastating shot of {CASCA} sitting in the wet grass in a torn cloak, staring at nothing, present and entirely absent at once",
   "She sits without moving. Her eyes track something that is not there. Her hands are open in her lap. She does not respond to anything.",
   say="Casca had gone somewhere inside herself that Guts could not follow, and she did not come back.",
   ref=["CASCA"], look="cold", tin="cut", seconds=6,
   sfx="Wind in wet grass, no voices, one person breathing shallowly, terrible quiet")

sh("820_guts_stands",
   "Powerful shot of {GUTS} getting to his feet on the empty moor, one arm ending in a crude iron prosthetic, one eye covered, the enormous sword used as a crutch, dawn behind him",
   "He plants the huge sword and hauls himself upright on it. The iron hand flexes. He straightens all the way up. Dawn light comes across the moor.",
   say="He had lost an eye, an arm, and everyone. He got up anyway. That is the whole of him, in one movement.",
   ref=["GUTS"], look="dawn", tin="dissolve", seconds=7,
   sfx="A great sword driven into wet earth, iron and leather, a body forcing itself upright, wind")

sh("830_black_swordsman",
   "Iconic final wide shot of {GUTS} walking away down an empty road at dawn in black, the enormous sword across his back, the brand at his neck, a vast empty landscape ahead, no one with him",
   "He walks away from camera down the road. The huge sword rides on his back. The road ahead is empty to the horizon. Very slow crane up and back.",
   say="He went looking for the thing that had worn his friend's face. He is still looking.",
   ref=["GUTS"], look="dawn", tin="dissolve", seconds=9,
   titles=[{"text": "BERSERK", "at": 4.0, "hold": 3.6, "scale": 0.05, "y": 0.44}],
   sfx="Boots on an empty road, a great sword shifting on a back, wind over open country, one distant bird")

# ─────────────────────────────────────────────────────────────── music cues
MUSIC = [
 ("m01_dead",   "010_field",   58, "bleak solo cello over a low drone, sparse funeral bell, cold and vast, dark orchestral, instrumental, no drums"),
 ("m02_child",  "030_child",   50, "grim medieval underscore, low viol drone, hand drum heartbeat, distant male voices humming one note, hopeless, instrumental"),
 ("m03_siege",  "060_siege",   70, "savage battle music, hammered timpani and taiko, low brass clusters, war drums, snarling strings, relentless, orchestral, instrumental"),
 ("m04_hawk",   "110_griffith_intro", 60, "noble ascendant theme, solo horn over warm strings, martial snare in the distance, proud and slightly cold, orchestral, instrumental"),
 ("m05_ride",   "200_hawks_ride", 66, "heroic mounted march, driving strings ostinato, bold brass, snare and timpani, banners and open country, orchestral, instrumental"),
 ("m06_war",    "240_battles", 60, "brutal orchestral war music, pounding percussion, brass stabs, choir shouting one syllable, chaotic, instrumental"),
 ("m07_fire",   "260_campfire", 64, "intimate nocturne, solo classical guitar and warm low strings, a single wooden flute, firelit and quiet, instrumental, no drums"),
 ("m08_casca",  "300_casca_story", 52, "tender melancholy theme, solo violin over sustained strings, harp, rain, bittersweet devotion, instrumental, no drums"),
 ("m09_rise",   "340_rise",    56, "triumphant royal fanfare turning slightly sour, full brass, bells, choir, grandeur with something wrong underneath, orchestral, instrumental"),
 ("m10_zodd",   "400_zodd_reveal", 68, "monstrous dread, sub bass pulses, bowed metal, low male choir, irregular percussion, inhuman, dark orchestral, instrumental"),
 ("m11_pivot",  "500_overheard", 54, "quiet devastating string adagio, solo cello line, sparse piano, the sound of understanding something too late, instrumental, no drums"),
 ("m12_duel",   "550_duel2",   58, "single combat in snow, taut string ostinato, muffled timpani, one high sustained violin, cold and precise, orchestral, instrumental"),
 ("m13_loss",   "580_griffith_alone", 50, "desolate solo piano with distant strings, snow, a dream ending, sparse and cold, instrumental, no drums"),
 ("m14_tower",  "620_year",    62, "oppressive dread, sustained low strings, dripping water percussion, a distant choir in pain, airless, dark ambient orchestral, instrumental"),
 ("m15_ruin",   "660_griffith_ruined", 54, "almost nothing, one sustained cello note, a music box slowing to a stop, unbearable restraint, instrumental, no drums"),
 ("m16_eclipse","700_eclipse", 76, "apocalyptic sacred horror, enormous latin-less choir, pipe organ clusters, bells rung wrong, sub bass, ecstatic and vile, orchestral, instrumental"),
 ("m17_price",  "730_answer",  60, "a chorus resolving from dissonance into a terrible major chord, brass and full choir, triumphant and obscene, orchestral, instrumental"),
 ("m18_after",  "800_after",   58, "grief laid completely bare, solo violin unaccompanied then warm strings entering, dawn, exhausted, instrumental, no drums"),
 ("m19_rise",   "820_guts_stands", 70, "grim resolve building, low strings ostinato, a single defiant horn, drums entering late, standing up again, orchestral, instrumental"),
]

film = collections.OrderedDict(
    title="BERSERK THE GOLDEN AGE",
    subtitle="a narrated summary of season one",
    ar="16:9", fps=24, seconds=6, tail=1.1,
    default_transition="cut",
    style_lora="qwen_image_2512_storybook_anime_lora.safetensors",
    style_strength=0.0,
    id_lora="ltx-2.3-id-lora-talkvid-3k.safetensors",
    id_strength=0.6,
    sheets=SHEETS,
    style=STYLE,
    characters=CHARS,
    voices=VOICES,
    music=[collections.OrderedDict(at_shot=a, prefix=p, bpm=b, key="D minor",
                                  seconds=s, level=1.0, tags=t)
           for (p, a, s, t), b in zip(MUSIC, [52,60,140,84,112,138,66,60,96,54,52,120,50,44,40,60,68,50,88])],
    shots=S,
)

json.dump(film, open(OUT, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
ids = [x["id"] for x in S]
assert len(ids) == len(set(ids)), "duplicate shot ids"
nar = sum(1 for x in S if x.get("say"))
dia = sum(1 for x in S if x.get("who"))
clips = sum(max(1, int(x.get("chain", 1))) for x in S)
print(f"wrote {OUT}")
print(f"  shots {len(S)}   clips {clips}   chained scenes {sum(1 for x in S if x.get('chain'))}")
print(f"  narrated {nar} (of which character dialogue {dia})")
print(f"  reference-locked {sum(1 for x in S if x.get('ref'))}   music cues {len(MUSIC)}")
print(f"  words of narration {sum(len(x['say'].split()) for x in S if x.get('say'))}")
