#!/usr/bin/env python3
"""studio/_tools/agency_sheet.py - one contact sheet per person, so the feed gets looked at.

The standing rule in this repo is that video and stills are judged by watching, not by a score.
Thirty posts is too many to open one at a time, so this lays each person's feed out as a single
sheet with the post key printed on each tile. A tile that fails - wrong face, broken hand, a
composition that reads as generated - gets regenerated by name:

    python3 studio/_tools/agency_sheet.py
    python3 studio/_tools/agency.py --posts --who naia-ferreira --only night-swim   # after deleting it
"""
import glob
import os

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "studio", "samples", "agency")
CW, CH, COLS, HEAD = 340, 425, 5, 22


def main():
    for d in sorted(glob.glob(os.path.join(SRC, "*"))):
        if not os.path.isdir(d):
            continue
        posts = sorted(f for f in os.listdir(d) if f.startswith("post_") and f.endswith(".png"))
        if not posts:
            continue
        rows = (len(posts) + COLS - 1) // COLS
        sheet = Image.new("RGB", (CW * COLS, (CH + HEAD) * rows), (22, 21, 20))
        dr = ImageDraw.Draw(sheet)
        for i, f in enumerate(posts):
            im = Image.open(os.path.join(d, f)).convert("RGB")
            w, h = im.size
            sc = min(CW / w, CH / h)
            im = im.resize((max(1, int(w * sc)), max(1, int(h * sc))), Image.LANCZOS)
            x = (i % COLS) * CW
            y = (i // COLS) * (CH + HEAD)
            sheet.paste(im, (x + (CW - im.size[0]) // 2, y + HEAD))
            dr.text((x + 5, y + 5), f[5:-4], fill=(235, 230, 222))
        out = os.path.join(SRC, "%s_sheet.jpg" % os.path.basename(d))
        sheet.save(out, quality=84)
        print("  %-18s %2d posts -> %s" % (os.path.basename(d), len(posts), out))


if __name__ == "__main__":
    main()
