#!/usr/bin/env python3
"""studio/_tools/model3d_index.py - the payload behind /model3d.

    python3 studio/_tools/model3d_index.py                 a human summary
    python3 studio/_tools/model3d_index.py --json          the payload the page reads
    python3 studio/_tools/model3d_index.py --character TERRA
    python3 studio/_tools/model3d_index.py --check         exit 1 if any asset is missing

WHAT THIS IS. Three agents produced the 3D work for TERRA and left it on disk as a
sample tree, two JSON reports, a markdown verdict and 885 MB of meshes and renders.
Nothing in the app reached any of it. This assembles that tree into one payload so
/model3d can show it, and so the next character's pipeline is discovered rather than
hand-listed.

WHAT IT DOES NOT DO. It measures nothing. Every number it returns is read out of
studio/samples/<slug>_3d/mesh/REPORT.json, which studio/_tools/terra_mesh.py wrote from
studio/_tools/mesh_doctor.py's own JSON. If a number here disagrees with a mesh, the
report is stale - regenerate it, do not edit this file. The only things authored here are
the VERDICT/FAILURE note tables below, and each one carries the section of
mesh/VERDICT.md it was read out of so it can be checked.

DISCOVERY. A character has a 3D pipeline if studio/samples/<id.lower()>_3d/ exists. That
is the whole contract - run the pipeline for NIKA into studio/samples/nika_3d/ with the
same layout and this tool finds her with no edit. Layout:

    <slug>_3d/source/RECOMMENDATION.json     which image to feed, and why
    <slug>_3d/source/*.png                   the matted candidates
    <slug>_3d/source/multiview_qwen/*.png    the four cardinals
    <slug>_3d/source/evidence/*.jpg          the sweeps behind the recommendation
    <slug>_3d/mesh/REPORT.json               every candidate, generated and measured
    <slug>_3d/mesh/VERDICT.md                which mesh won, written after looking
    <slug>_3d/mesh/*.glb                     the meshes
    <slug>_3d/mesh/views/*.jpg|*.mp4         orbit strips, head close-ups, turntables
    <slug>_3d/mesh/print/*.stl|*.3mf         the sliceable deliverables

EVERY ASSET IS CHECKED AGAINST THE FILESYSTEM. A candidate that names a render which is
not there is reported in `missing` rather than shipped as a broken <img>, because the
cast page used to render a green tick for a string being non-empty and that is exactly
how a page ends up lying.
"""
import argparse
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))      # studio/
ROOT = os.path.dirname(HERE)                                            # the repo
SAMPLES = os.path.join(HERE, "samples")

# ---------------------------------------------------------------------------
# The judgement layer.
#
# Everything above this line is filesystem and JSON. Everything in these three tables is
# somebody's opinion, so each row carries the document and section it came from. The page
# labels them JUDGED for the same reason mesh/VERDICT.md does: a number you can re-measure
# and a view somebody formed by opening a picture are not the same kind of claim.
# ---------------------------------------------------------------------------

# state: win | alt | ok | weak | fail.  Text quoted or condensed from mesh/VERDICT.md.
NOTES = {
    "I_s512_thr045": ("win", "THE WINNER. Octree 512 at surface-net threshold 0.45. "
                      "Repaired at voxel-res 900 and shipped. Holds lidded almond eyes, "
                      "nose, mouth, earrings and the hair ribbon, and 1.66% of its "
                      "surface is under 1 mm at a 150 mm print against the runner-up's "
                      "6.93%.", "VERDICT.md 1, 2"),
    "D_s512": ("alt", "Runner-up, shipped alongside as ALT_D_thr060_* so the threshold "
               "trade-off can be re-checked without regenerating anything. Identical to "
               "the winner except the extractor threshold, which is the workflow default "
               "0.60. Slightly crisper features; 4x more sub-millimetre surface.",
               "VERDICT.md 1, 2"),
    "C_s384": ("ok", "The middle rung of the octree ladder. Also the only candidate whose "
               "repair FAILED at mesh_doctor's default settings - it came back "
               "fixed_watertight false and said so rather than shipping a broken solid. "
               "Raising --voxel-res is the fix.", "VERDICT.md 2, 7b"),
    "B_square": ("ok", "The octree-256 baseline, and the framing control that beats "
                 "A_portrait_crop: same seed, same settings, padded square first. One "
                 "island against A's eleven.", "VERDICT.md 4"),
    "J_s512_seed": ("ok", "Seed 12345, otherwise identical to D_s512. Came back with "
                    "visibly different leg thickness, a shorter skirt and a different "
                    "hair fall. This is the size of the noise floor: do not attribute a "
                    "difference between two settings to the settings without holding the "
                    "seed.", "VERDICT.md 2"),
    "A_portrait_crop": ("weak", "CONTROL - the raw 1664x2432 portrait handed straight to "
                        "CLIPVisionEncode with crop=center, i.e. what a naive run of "
                        "workflow 24 does. The preprocessor keeps the middle 1664 of 2432 "
                        "rows, so 15.8% off each end is thrown away. The mesh survives but "
                        "comes back stockier, surface-noisier, with 11 floating islands "
                        "against B_square's 1.", "VERDICT.md 4"),
    "K_s512_thr070": ("weak", "Threshold 0.70. The wrong end of the printability dial - "
                      "the worst sub-millimetre fraction of the three thresholds tested. "
                      "Lower the threshold, do not raise it.", "VERDICT.md 2"),
    "H_s384_l8192": ("weak", "Latent resolution doubled to 8192 at octree 384. The face "
                     "got MUSHIER and the hair degenerated into tangled sausages. Latent "
                     "tokens are not a substitute for octree resolution - 512/4096 beats "
                     "384/8192 clearly. Spend the budget on octree.", "VERDICT.md 2"),
    "L_s512_basic": ("fail", "VoxelToMesh algorithm 'basic' instead of 'surface net'. A "
                     "fuzzy, sugar-coated blob whose silhouette dissolves. Not close. "
                     "Surface net is correct despite being the source of the non-manifold "
                     "edges.", "VERDICT.md 2"),
    "N_grid2x2": ("fail", "The tiling workaround: all four cardinals composited into one "
                  "square image down the ordinary single-view path. 1.16M faces of "
                  "floating slabs and fragments. CLIP-vision conditioning does not "
                  "decompose a contact sheet into viewpoints.", "VERDICT.md 3"),
    "E_mv256": ("fail", "Hunyuan3Dv2ConditioningMultiView with all four cardinals. A cloud "
                "of disconnected specks in a 0.11-unit-thick slab - 12,108 faces, 134 "
                "vertex islands, 26% non-manifold. Not a worse figure. Noise.",
                "VERDICT.md 3"),
    "F_mv384": ("fail", "The same multi-view failure at octree 384. Raising the octree "
                "does not rescue it, which is the first sign the input conditioning is "
                "wrong rather than the resolution.", "VERDICT.md 3"),
    "G_mv512": ("fail", "The same multi-view failure at octree 512.", "VERDICT.md 3"),
    "MV1_single_img": ("fail", "THE DECISIVE CELL. ONE slot of the MultiView node, holding "
                       "the exact image B_square used. Those pixels make an excellent "
                       "figure through Hunyuan3Dv2Conditioning and specks through this "
                       "node. View count is not the variable. Image provenance is not the "
                       "variable. The node is.", "VERDICT.md 3"),
    "MV1_mv_img": ("fail", "One slot, the qwen front render instead. Fails identically, "
                   "which rules out image provenance.", "VERDICT.md 3"),
    "MV2_front_back": ("fail", "Two slots. A different failure - a hollow inside-out box "
                       "of 117k faces rather than specks.", "VERDICT.md 3"),
    "MV4_lrswap": ("fail", "Four slots with left and right exchanged, to rule out a "
                   "handedness convention. Fails identically.", "VERDICT.md 3"),
}

# The repair ladder. mesh_doctor's repair resolution is a separate dial from generation
# and it has its own renders, so it gets its own row rather than being folded into the
# candidate it repaired.
REPAIRS = {
    "D_s512": [
        {"label": "voxel-res 320 (mesh_doctor default)", "voxel_res": 320,
         "glb": "D_s512_fixed.glb", "orbit": "D_s512_fixed_orbit.jpg",
         "head": "D_s512_fixed_head.jpg", "state": "fail",
         "note": "0.47 mm per voxel at a 150 mm print. The face is DESTROYED - a terraced "
                 "mass with no eyes, no nose and no ribbon - while the full-body "
                 "silhouette still reads as Terra at contact-sheet scale. That is exactly "
                 "what makes it dangerous. 5 s."},
        {"label": "voxel-res 640", "voxel_res": 640, "glb": "D_s512_fix640.glb",
         "orbit": "D_s512_fix640_orbit.jpg", "head": "D_s512_fix640_head.jpg",
         "state": "weak",
         "note": "0.23 mm per voxel. Partial - the eye sockets return, the nose and mouth "
                 "are still terraced. 17 s, 5.4 GB."},
        {"label": "voxel-res 900", "voxel_res": 900, "glb": "D_s512_fix900.glb",
         "orbit": "D_s512_fix900_orbit.jpg", "head": "D_s512_fix900_head.jpg",
         "turntable": "D_s512_fix900_turntable.mp4", "state": "ok",
         "note": "0.167 mm per voxel. Good - lidded eyes, nose, mouth, ears and ribbon all "
                 "legible. 37 s, 10.7 GB host RAM, 2.65M faces out."},
    ],
    "I_s512_thr045": [
        {"label": "voxel-res 320 (mesh_doctor default)", "voxel_res": 320,
         "glb": "I_s512_thr045_fixed.glb", "state": "fail",
         "note": "Watertight, and the face is gone for the same reason it is gone on "
                 "D_s512_fixed. Kept only because REPORT.json's cross-candidate thickness "
                 "table was measured on these 320 repairs, which is why those absolute "
                 "numbers are optimistic."},
        {"label": "voxel-res 900 - SHIPPED", "voxel_res": 900,
         "glb": "I_thr045_fix900.glb", "orbit": "I_thr045_fix900_orbit.jpg",
         "head": "I_thr045_fix900_head.jpg",
         "turntable": "I_thr045_fix900_turntable.mp4", "state": "win",
         "note": "The delivered solid. 2,673,708 faces, 0 boundary edges, 0 non-manifold "
                 "edges, 1 island, winding consistent, is_volume true, blocking []."},
    ],
}

# ---------------------------------------------------------------------------
# THE SHIPPED OBJECT IS NOT THE OBJECT REPORT.json's `fixed_*` COLUMNS DESCRIBE.
#
# This nearly put two contradictions on the page. terra_mesh.py's cross-candidate
# comparison repaired every candidate at mesh_doctor's default --voxel-res 320, so
# REPORT.json's fixed_faces, bed_contact_mm2, overhang and thickness columns all describe
# a 320 repair. The file that was actually exported is the voxel-res 900 repair, which is
# a different mesh: 2.67M faces against 333k, 200.9 mm2 of bed contact against 172.0.
#
# Those 320 columns are still the right thing to compare candidates on - every candidate
# got the same treatment - so they stay on each candidate card, labelled. The audit panel
# must use the numbers below instead, and they are quoted from mesh/VERDICT.md, which is
# the only place the delivered solid was measured.
# ---------------------------------------------------------------------------
SHIPPED_FINAL = {
    "I_s512_thr045": {
        "mesh": "I_thr045_fix900.glb", "voxel_res": 900,
        "faces": 2673708, "boundary_edges": 0, "nonmanifold_edges": 0, "islands": 1,
        "winding": True, "is_volume": True, "blocking": [], "genus": 329,
        "size_mm": [82.9, 49.3, 150.0], "zmin_mm": 0.0, "volume_cm3": 55.5,
        "bed_contact_mm2": 200.9, "overhang_frac": 0.0779, "flat_ceiling_frac": 0.0322,
        "src": "mesh/VERDICT.md 1, 6",
    },
}

# Thickness at the SHIPPED repair, not at the voxel-res 320 repair REPORT.json's
# comparison table used. Quoted from mesh/VERDICT.md sections 2 and 6, which is the only
# place this pair was re-measured at 900.
SHIPPED_THICKNESS = {
    "I_s512_thr045": {"under_1mm_150": 1.66, "p10_150_mm": 1.68, "under_03mm_150": 0.54},
    "D_s512": {"under_1mm_150": 6.93, "p10_150_mm": 1.19, "under_03mm_150": None},
}

# Why each rejected source image was rejected. Read out of the source stage's own findings;
# "rejected" with no reason beside it is worth nothing to the next person.
REJECTED_NOTES = {
    "A_out_L3_s1_rgba.png":
        "THE GREY PLATE CELL. Same seed and pose as the chosen image; only the background "
        "colour differs. BiRefNet severed the bare pale forearm here - the hand survived as "
        "a floating island of 1.33% of the figure area against 0.04% on dark blue.",
    "D_away_L3_s1_rgba.png":
        "Pose vocabulary 'arms away'. The arms did not clear the torso for their whole "
        "length, so the mesh would fuse arm to body with nothing able to separate them "
        "afterwards.",
    "E_tpose_L3_rgba.png":
        "The danbooru tag 'spread arms' - the tag that literally MEANS a T-pose. It "
        "returned arms near the hips, at both LoRA strengths tested. This is the finding "
        "that disproved the LoRA hypothesis.",
    "F_tamehair_rgba.png":
        "'ponytail, hair behind back', an attempt to reduce the hair volume before it "
        "became an overhang problem. It did not work - the volume is trained into the LoRA "
        "and is not reachable from a hair tag.",
}

# The failure gallery. Task-critical: a candidate that came out a blob is the most useful
# thing on this page for anyone about to try this. Each entry names the picture that shows
# it, so nothing here has to be taken on trust.
FAILURES = [
    {"id": "multiview",
     "title": "Multi-view conditioning returns a cloud of specks",
     "looks_like": "Not a worse figure - noise. 12,108 faces scattered through a slab 0.11 "
                   "units thick, 134 vertex islands, 26% non-manifold. At every octree "
                   "resolution, at every view count, with left and right swapped.",
     "image": "mesh/views/E_mv256_orbit.jpg",
     "image2": "mesh/views/MV1_single_img_orbit.jpg",
     "image2_caption": "MV1_single_img - ONE slot, holding the exact image that makes an "
                       "excellent figure through the single-view node.",
     "cause": "Hunyuan3Dv2ConditioningMultiView adds a 1-D sincos view embedding per view "
              "and concatenates the token sequences (comfy_extras/nodes_hunyuan3d.py:77-90). "
              "That is the Hunyuan3D-2mv conditioning format. Only the single-view "
              "hunyuan_3d_v2.1 checkpoint is installed, and it has never seen an additive "
              "view embedding - so even ONE view through that node is out of distribution.",
     "fix": "Use Hunyuan3Dv2Conditioning with one good view. To actually get multi-view on "
            "this box you must download a hunyuan3d-2mv checkpoint; no amount of image "
            "preparation helps.",
     "cost": "Roughly two hours of the mesh stage, spent because the brief named multi-view "
             "as the most likely big win.",
     "src": "VERDICT.md 3"},
    {"id": "grid",
     "title": "Tiling four views into one image does not fake multi-view",
     "looks_like": "1.16M faces of floating slabs and fragments.",
     "image": "mesh/views/N_grid2x2_orbit.jpg",
     "cause": "CLIP-vision conditioning encodes a picture. It does not decompose a contact "
              "sheet into viewpoints - it sees one strange flat image containing four small "
              "people.",
     "fix": "There is no workaround at the image level. Feed one view.",
     "src": "VERDICT.md 3"},
    {"id": "repair320",
     "title": "Repairing at the default resolution destroys the face, and the body looks fine while it happens",
     "looks_like": "A terraced Minecraft mass where the head was - no eyes, no nose, no "
                   "ribbon. The full-body silhouette still reads as the character at "
                   "contact-sheet scale, which is what makes this the most dangerous "
                   "failure on the page.",
     "image": "mesh/views/D_s512_fixed_head.jpg",
     "image_caption": "repair --voxel-res 320, the default",
     "image2": "mesh/views/D_s512_fix900_head.jpg",
     "image2_caption": "the same mesh at --voxel-res 900",
     "cause": "The dial counts voxels along the LONGEST axis. A standing figure's longest "
              "axis is her height, so a slender subject is penalised where a squat one is "
              "not. An anime eyelid crease is roughly 0.5 mm at a 150 mm print; at 320 one "
              "voxel is 0.47 mm and the crease cannot survive.",
     "fix": "voxel-res at least 6x the octree resolution you decoded at, or put another "
            "way, at most 0.2 mm per voxel at your intended print height. 900 cost 37 s and "
            "10.7 GB of host RAM here.",
     "src": "VERDICT.md 5"},
    {"id": "crop",
     "title": "The CLIP centre crop eats the ends of a portrait",
     "looks_like": "15.8% off the top and 15.8% off the bottom of a 1664x2432 source - in "
                   "practice the top of the hair ribbon and the tips of the boots. The mesh "
                   "survives and is degraded: 11 floating islands against 1, and the wrap "
                   "skirt read as a long fringed cloth to the ankles.",
     "image": "mesh/views/EVIDENCE_clip_preprocess.jpg",
     "image_caption": "what CLIPVisionEncode actually receives, dumped by running "
                      "comfy.clip_model.clip_preprocess directly",
     "cause": "CLIPVisionEncode's crop=center squares a portrait by throwing away the ends.",
     "fix": "Pad the source square yourself before it reaches the encoder, or set "
            "crop=none, which letterboxes instead. Both verified.",
     "src": "VERDICT.md 4"},
    {"id": "latent",
     "title": "Latent resolution is not a substitute for octree resolution",
     "looks_like": "A mushier face and hair degenerating into tangled sausages, at higher "
                   "cost than the setting that works.",
     "image": "mesh/views/H_s384_l8192_head.jpg",
     "cause": "Doubling EmptyLatentHunyuan3Dv2 to 8192 tokens at octree 384 spends the "
              "budget in the wrong place. Octree 512 at latent 4096 beats it clearly.",
     "fix": "Spend on octree_resolution. It is a topology dial as well as a detail dial - "
            "raising it 256 to 512 cut the non-manifold edge fraction 6.5x, for 2.8x wall "
            "clock and 900 MiB more VRAM.",
     "src": "VERDICT.md 2"},
    {"id": "basic",
     "title": "VoxelToMesh algorithm 'basic' is not a serious option",
     "looks_like": "A fuzzy, sugar-coated blob whose silhouette dissolves. 868k faces of "
                   "noise.",
     "image": "mesh/views/L_s512_basic_orbit.jpg",
     "cause": "The basic extractor cannot hold a thin surface at this scale.",
     "fix": "surface net, despite it being the source of the non-manifold edges the repair "
            "stage exists to remove.",
     "src": "VERDICT.md 2"},
    {"id": "sourceset",
     "title": "The character's existing 16-view turnaround cannot feed a 3D pipeline",
     "looks_like": "Three of the six usable views are cropped by the frame; the cape is "
                   "smooth and short in two of them and floor-length, shredded and stained "
                   "in the others - two different garments; the arms are against the body "
                   "in all sixteen; and the mattes carry 17 detached fragments on the front "
                   "view alone.",
     "image": "source/evidence/sheet_views.jpg",
     "cause": "The turnaround was built to prove face consistency, not to be scale-matched "
              "geometry input. A cropped view has no common scale with a complete one.",
     "fix": "Render a purpose-built source: one seed, one pose, one plate, arms open, whole "
            "figure in frame. Watch out for the figure-height column reading 95-100% across "
            "cropped views - that looks like scale agreement and is the opposite of it.",
     "src": "source/RECOMMENDATION.json"},
    {"id": "arms",
     "title": "The danbooru tag that means a T-pose does not open the arms",
     "looks_like": "Arms near the hips at both LoRA strengths tested. Five pose "
                   "vocabularies were swept; only 'outstretched arms' opened her with air "
                   "on both sides for the arms' whole length.",
     "image": "source/evidence/sheet_pose.jpg",
     "cause": "The going hypothesis was the LoRA - all 16 training views have arms down. "
              "Sweeping strength alongside the pose words disproves it: the pose opens at "
              "full 0.50 strength. The words are what weld the arms, not the weights.",
     "fix": "'outstretched arms'. Keep the character card's measured LoRA strength; "
            "dropping it is not a free win - one cell drifted off the anime engine "
            "entirely and returned a smooth 3D-render doll.",
     "src": "source/RECOMMENDATION.json"},
    {"id": "shadow",
     "title": "A negation in the positive prompt does not render",
     "looks_like": "'no cast shadow' in the POSITIVE prompt still drew a dark shadow pool "
                   "at her feet - which mattes as part of the figure and becomes geometry.",
     "image": "source/evidence/sheet_light_out.jpg",
     "cause": "A diffusion model draws the nouns it is given. 'shadow' is one of them.",
     "fix": "Move shadow, drop shadow, floor, ground and reflection to the NEGATIVE prompt.",
     "src": "source/RECOMMENDATION.json"},
    {"id": "plate",
     "title": "The background plate colour is a matting variable, not decoration",
     "looks_like": "On the project's usual grey plate BiRefNet SEVERED a bare pale forearm "
                   "- the hand survived as a floating island of 1.33% of the figure area. "
                   "Same seed, same pose, dark blue plate: 0.04%, forearm continuous.",
     "image": "source/evidence/sheet_matte.jpg",
     "cause": "Pale skin on pale grey is not enough contrast for the matter. Every stray "
              "island in the matte is a floating shell in the mesh downstream.",
     "fix": "Matte against a plate that contrasts with the SKIN, not just with the costume. "
            "Dark blue worked here (n=2, not swept).",
     "src": "source/RECOMMENDATION.json"},
]

# The five stages, in order, with the tool that runs each. Shown as the page's spine.
STAGES = [
    {"n": 1, "id": "source", "title": "Source",
     "tool": "studio/_tools/terra_3d_source.py",
     "what": "Render the character large, arms clear of the body, no cast shadow, on a "
             "plate that contrasts with her skin. Matte to RGBA. Look at the alpha."},
    {"n": 2, "id": "prep", "title": "Prep",
     "tool": "studio/_tools/terra_mesh.py prep",
     "what": "Alpha-crop, composite onto white, pad SQUARE. The square is not cosmetic - "
             "it is what stops CLIPVisionEncode throwing away the ends of the figure."},
    {"n": 3, "id": "generate", "title": "Generate",
     "tool": "studio/_tools/terra_mesh.py gen",
     "what": "Hunyuan3D 2.1 through workflow 24. Single-view conditioning, octree 512, "
             "VoxelToMesh surface net at threshold 0.45."},
    {"n": 4, "id": "repair", "title": "Repair",
     "tool": "studio/_tools/mesh_doctor.py repair",
     "what": "Voxel remesh - rasterise, flood-fill the interior, re-extract. Nothing else "
             "removes the interior membranes surface net leaves. Resolution 900, not the "
             "default 320."},
    {"n": 5, "id": "print", "title": "Print spec",
     "tool": "studio/_tools/mesh_doctor.py scale/thickness/overhang/export",
     "what": "Scale to millimetres Z-up, measure wall thickness and overhang, export STL "
             "and 3MF, and re-load what was written to prove it is still a closed solid."},
]

DELIVERABLE_NOTES = {
    # --- print/ : mesh_prep.py's plinth stage. THIS is what you slice. ---
    "TERRA_150mm.stl":
        ("win", "THE DELIVERABLE. 80.85 x 54.45 x 150.00 mm, zmin exactly 0, 67.13 cm3, "
                "3,265,786 faces, one closed manifold solid fused onto a 50 mm plinth. "
                "Bed contact 1,953 mm2. Re-loaded from disk and re-measured "
                "independently of the tool that wrote it."),
    "TERRA_200mm_fdm.stl":
        ("win", "THE SAME SOLID AT 200 mm, which is the size to print on FDM: "
                "107.80 x 72.60 x 200.00 mm, 159.11 cm3. A uniform scale of a closed "
                "solid stays closed, and every feature grows by the same 4/3, so only "
                "0.16% of surface is under the 1.0 mm nozzle floor against 0.29% at "
                "150 mm and the thinnest 1% is 1.59 mm. Re-loaded and re-measured."),
    "TERRA_150mm.3mf":
        ("ok", "The same solid as 3MF, which unlike STL carries its units - open this if "
               "your slicer asks what scale the file is in. 30 MB against 163 MB."),
    "TERRA_150mm.glb":
        ("ok", "For LOOKING AT, not for slicing. Y-up, and no slicer wants it."),
    "TERRA_150mm_lighter-file.3mf":
        ("ok", "The lighter build as 3MF - 18 MB, and it carries its units."),
    "TERRA_150mm_lighter-file.stl":
        ("ok", "Same treatment at a 0.20 mm voxel instead of 0.15: 1.83M faces and 91 MB "
               "against 3.27M and 163 MB, watertight, and printability is "
               "indistinguishable. Costs a visibly softer face. Take it if your slicer "
               "struggles with the primary."),
    "TERRA_150mm_resin-detail.stl":
        ("ok", "Thickened to the 0.3 mm resin floor rather than the 1.0 mm FDM one, so "
               "less material was added. Resin only."),
    "TERRA_150mm_minimal-edit.stl":
        ("weak", "Repaired and based but NOT thickened or crevice-closed - the honest "
                 "control. 1.23% of surface under 0.8 mm against the primary's 0.21%, "
                 "and genus 308 against 43. Shipped so the treatment can be re-judged."),
    # --- mesh/print/ : the mesh stage's export, BEFORE a base was added. ---
    "TERRA_WINNER_150mm_resin.stl":
        ("ok", "THE SAME FIGURE WITH NO BASE - 83.41 x 49.78 x 150.00 mm, 60.73 cm3, "
               "and only 148 mm2 of bed contact, because she stands on two pointed boot "
               "tips. Watertight, but it will not stay on a plate. Take this one only if "
               "you intend to add your own base or re-pose her."),
    "TERRA_WINNER_150mm_resin.3mf":
        ("ok", "The same solid as 3MF, which unlike STL carries its units. Reloads "
               "watertight through trimesh; NOT verified in a slicer."),
    "TERRA_WINNER_200mm_fdm.stl":
        ("ok", "The winner at 200 mm, which is what FDM wants: 1.61% under the 1.0 mm "
               "floor against 6.93% at 150 mm on the same ladder."),
    "ALT_D_thr060_150mm.stl":
        ("weak", "The runner-up at the workflow's default threshold 0.60, shipped so the "
                 "threshold trade-off can be re-checked without regenerating. Fails the "
                 "project's 5% sub-millimetre convention at this height."),
    "ALT_D_thr060_150mm.3mf": ("weak", "The runner-up as 3MF."),
    "ALT_D_thr060_200mm.stl":
        ("ok", "The runner-up at 200 mm, where it passes."),
}

MIME3D = {".glb": "model/gltf-binary", ".stl": "model/stl", ".3mf": "model/3mf",
          ".spz": "application/octet-stream", ".obj": "model/obj",
          ".ply": "application/octet-stream"}


# ---------------------------------------------------------------------------
# filesystem helpers
# ---------------------------------------------------------------------------
def _read_json(p, default=None):
    try:
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return default


def _read_text(p):
    try:
        with open(p, encoding="utf-8", errors="replace") as f:
            return f.read()
    except Exception:
        return None


class Assets(object):
    """Resolve a path inside one character's 3D tree to a /samples URL, or record it as
    missing. Nothing reaches the page without passing through here, which is the whole
    reason the page cannot show a broken image."""

    def __init__(self, root_abs, root_url):
        self.root_abs = root_abs
        self.root_url = root_url
        self.missing = []
        self.bytes = 0
        self.n = 0

    def url(self, rel, required=True):
        if not rel:
            return None
        p = os.path.join(self.root_abs, rel)
        if not os.path.isfile(p):
            if required:
                self.missing.append(rel)
            return None
        self.n += 1
        self.bytes += os.path.getsize(p)
        return self.root_url + "/" + rel.replace(os.sep, "/")

    def file(self, rel, required=True):
        """Like url(), but returns {url, bytes, name} - for anything with a download link,
        because a 133 MB button that does not say so is a trap."""
        u = self.url(rel, required)
        if not u:
            return None
        p = os.path.join(self.root_abs, rel)
        return {"url": u, "bytes": os.path.getsize(p),
                "name": os.path.basename(rel),
                "ext": os.path.splitext(rel)[1].lower()}


def _listdir(d, suffixes=None):
    if not os.path.isdir(d):
        return []
    out = []
    for fn in sorted(os.listdir(d)):
        if suffixes and not fn.lower().endswith(tuple(suffixes)):
            continue
        if os.path.isfile(os.path.join(d, fn)):
            out.append(fn)
    return out


# ---------------------------------------------------------------------------
# the cast, and which of them have a 3D pipeline on disk
# ---------------------------------------------------------------------------
def _cards():
    d = os.path.join(HERE, "characters")
    out = {}
    for fn in _listdir(d, [".json"]):
        cid = fn[:-5]
        out[cid] = _read_json(os.path.join(d, fn), {}) or {}
    return out


def _slug(cid):
    return "".join(c for c in cid.lower() if c.isalnum() or c in "-_")


def _pipeline_dir(cid):
    return os.path.join(SAMPLES, _slug(cid) + "_3d")


def characters():
    """Every cast member, with whether a 3D pipeline exists for them and how far it got.

    Deliberately lists the ones with NOTHING too. The page's job is partly to say `this
    has been done once and here is the recipe for the next one`, and a list that silently
    omits the six characters nobody has printed cannot say that."""
    out = []
    for cid, card in sorted(_cards().items()):
        d = _pipeline_dir(cid)
        rep = os.path.join(d, "mesh", "REPORT.json")
        rec = os.path.join(d, "source", "RECOMMENDATION.json")
        prints = (_listdir(os.path.join(d, "print"), [".stl", ".3mf"])
                  + _listdir(os.path.join(d, "mesh", "print"), [".stl", ".3mf"]))
        if not os.path.isdir(d):
            state = "none"
        elif prints and os.path.exists(rep):
            state = "printable"
        elif os.path.exists(rep):
            state = "meshed"
        elif os.path.exists(rec):
            state = "sourced"
        else:
            state = "started"
        r = _read_json(rep, {}) or {}
        out.append({
            "id": cid,
            "name": card.get("name") or card.get("title") or cid,
            "one_line": card.get("one_line") or card.get("desc") or card.get("summary"),
            "dir": os.path.relpath(d, ROOT).replace(os.sep, "/") if os.path.isdir(d) else None,
            "state": state,
            "candidates": len(r.get("candidates") or []),
            "prints": len(prints),
        })
    return out


# ---------------------------------------------------------------------------
# one character's payload
# ---------------------------------------------------------------------------
def _source(a, d, report=None):
    rec = _read_json(os.path.join(d, "source", "RECOMMENDATION.json"), {}) or {}
    alpha = _read_json(os.path.join(d, "source", "alpha_report.json"), {}) or {}
    sv = rec.get("single_view") or {}
    mv = rec.get("multi_view") or {}

    def img(rel, caption=None, required=True):
        f = a.file(rel, required)
        if f:
            f["caption"] = caption
        return f

    chosen = img("source/" + (sv.get("use") or ""), "the recommended single view") \
        if sv.get("use") else None
    runner = None
    ru = (sv.get("runner_up") or "").split(" - ")[0].strip()
    if ru:
        runner = img("source/" + ru, (sv.get("runner_up") or ""), required=False)

    others = []
    for fn in _listdir(os.path.join(d, "source"), [".png", ".jpg", ".webp"]):
        if sv.get("use") == fn or (runner and runner["name"] == fn):
            continue
        f = img("source/" + fn, None, required=False)
        if f:
            others.append(f)

    # Which of the rendered views the prep stage actually FED. The source stage rendered
    # six and recommended four; a page that shows all six without saying which were used
    # is quietly wrong about what produced the mesh.
    fed = set()
    for slot in ((report or {}).get("prep") or {}).get("multiview", {}).values():
        if isinstance(slot, dict) and slot.get("src"):
            fed.add(os.path.basename(slot["src"]))

    cardinals = []
    mvdir = (mv.get("use") or "").split()[0].strip("/ ") or "multiview_qwen"
    for fn in _listdir(os.path.join(d, "source", mvdir), [".png", ".jpg"]):
        f = img("source/%s/%s" % (mvdir, fn), None, required=False)
        if f:
            f["fed"] = fn in fed
            cardinals.append(f)

    rejected = []
    for fn in _listdir(os.path.join(d, "source", "rejected"), [".png", ".jpg"]):
        f = img("source/rejected/" + fn, REJECTED_NOTES.get(fn), required=False)
        if f:
            rejected.append(f)

    EVID = {
        "sheet_pose.jpg": "POSE - five pose vocabularies at two LoRA strengths. Only "
                          "'outstretched arms' opens the arms.",
        "sheet_light_out.jpg": "LIGHT - 'no cast shadow' as positive words still draws the "
                               "shadow. Only the negative prompt removes it.",
        "sheet_matte.jpg": "PLATE - grey plate against dark blue, same seed. The grey one "
                           "severs a bare forearm.",
        "sheet_views.jpg": "THE EXISTING TURNAROUND - why it cannot be used: cropped views, "
                           "two different capes, arms welded to the torso, dirty mattes.",
        "sheet_mv.jpg": "TEXT-CONDITIONED TURNAROUND - framing fixed, costume still "
                        "bistable: gold bodice in one view, red in five.",
        "sheet_mvq.jpg": "IMAGE-CONDITIONED TURNAROUND - the same costume in all six views. "
                         "The set that was eventually built, and that nothing on this box "
                         "can eat.",
    }
    evidence = []
    for fn in _listdir(os.path.join(d, "source", "evidence"), [".jpg", ".png"]):
        f = img("source/evidence/" + fn, EVID.get(fn), required=False)
        if f:
            evidence.append(f)

    return {"recommendation": rec, "alpha": alpha, "chosen": chosen, "runner_up": runner,
            "others": others, "cardinals": cardinals, "rejected": rejected,
            "evidence": evidence, "multiview_dir": mvdir}


def _candidates(a, d, report):
    out = []
    for c in report.get("candidates") or []:
        name = c.get("name") or ""
        row = dict(c)
        # Absolute paths in REPORT.json are the mesh stage's own; re-resolve by filename
        # so a moved tree still works and a missing render is reported rather than shown.
        row["orbit"] = a.url("mesh/views/%s_orbit.jpg" % name, required=False)
        row["head"] = a.url("mesh/views/%s_head.jpg" % name, required=False)
        row["turntable"] = a.url("mesh/views/%s_turntable.mp4" % name, required=False)
        row["glb"] = a.file("mesh/%s.glb" % name, required=False)
        row["glb_fixed"] = a.file("mesh/%s_fixed.glb" % name, required=False)
        row.pop("orbit_sheet", None)
        row.pop("head_sheet", None)
        state, note, src = NOTES.get(name, ("ok", None, None))
        row["state"] = state
        row["note"] = note
        row["note_src"] = src
        reps = []
        for r in REPAIRS.get(name, []):
            rr = dict(r)
            rr["glb"] = a.file("mesh/" + r["glb"], required=False)
            rr["orbit"] = a.url("mesh/views/" + r["orbit"], required=False) \
                if r.get("orbit") else None
            rr["head"] = a.url("mesh/views/" + r["head"], required=False) \
                if r.get("head") else None
            rr["turntable"] = a.url("mesh/views/" + r["turntable"], required=False) \
                if r.get("turntable") else None
            reps.append(rr)
        row["repairs"] = reps
        row["shipped_thickness"] = SHIPPED_THICKNESS.get(name)
        out.append(row)
    return out


def _splats(a, d, report):
    out = []
    for name, s in sorted((report.get("splat") or {}).items()):
        out.append({
            "name": name,
            "gaussians": s.get("num_gaussians"),
            "wall_s": s.get("wall_s"),
            "vram_peak_mib": (s.get("vram") or {}).get("peak_mib"),
            "mp4": a.url("mesh/%s.mp4" % name, required=False),
            "spz": a.file("mesh/%s.spz" % name, required=False),
        })
    return out


def _deliverables(a, d):
    """TWO STAGES WRITE DELIVERABLES AND ONLY THE SECOND IS SLICEABLE.

    mesh/print/ is the mesh stage's export - correct topology, but the figure stands on
    two boot tips (148 mm2 of bed contact, measured). print/ is mesh_prep.py's later
    output: the same figure fused onto a 50 mm plinth (1,953 mm2). This function was
    written before the second stage existed and listed only the first, which meant the
    page offered a model that falls off the plate and labelled it THE DELIVERABLE.
    Both stages are listed - the bare one is what you take to re-pose or re-base her -
    but print/ is scanned first and carries the winner."""
    out = []
    for sub in ("print", "print/alt", "mesh/print"):
        subdir = os.path.join(d, *sub.split("/"))
        for fn in _listdir(subdir, [".stl", ".3mf", ".obj", ".glb"]):
            f = a.file(sub + "/" + fn)
            if not f:
                continue
            state, note = DELIVERABLE_NOTES.get(fn, ("ok", None))
            f["state"] = state
            f["note"] = note
            f["stage"] = "bare" if sub.startswith("mesh/") else "plinth"
            f["mime"] = MIME3D.get(f["ext"], "application/octet-stream")
            out.append(f)
    # Winner files first, then the alternates. Without the ALT test an alphabetically
    # early alternate lands above the thing you are meant to download.
    out.sort(key=lambda f: (0 if f["state"] == "win" else 1 if f["state"] == "ok" else 2,
                            1 if f["name"].startswith("ALT") else 0, f["name"]))
    return out


def _failures(a):
    """Resolve the failure gallery's pictures to URLs.

    They are relative paths in the FAILURES table above, and shipping them unresolved is
    exactly what happened the first time - the page rendered ten captions and no pictures,
    which is worse than useless on the section whose whole point is what a wrong one looks
    like. Every path goes through Assets like everything else, so one that is not on disk
    comes back None and the page draws the entry without it rather than a broken image."""
    out = []
    for f in FAILURES:
        g = dict(f)
        g["image"] = a.url(f["image"], required=False)
        if f.get("image2"):
            g["image2"] = a.url(f["image2"], required=False)
        out.append(g)
    return out


def _audit(cands):
    """The printability audit for whichever candidate is marked the winner.

    EVERY NUMBER HERE DESCRIBES THE FILE THAT WAS ACTUALLY EXPORTED, which is not the
    object REPORT.json's `fixed_*` columns describe - those were measured on voxel-res 320
    repairs so that candidates could be compared under identical treatment. Mixing the two
    put two contradictions on this page before it was looked at: an audit reading 332,950
    triangles beside prose saying 2.67M, and 172.0 mm2 of bed contact beside prose saying
    200.9. So the audit reads SHIPPED_FINAL and says which document each row came from.
    """
    win = next((c for c in cands if c.get("state") == "win"), None)
    if not win:
        return None
    st = win.get("shipped_thickness") or {}
    fin = SHIPPED_FINAL.get(win.get("name"))
    fsrc = (fin or {}).get("src", "mesh/REPORT.json")

    def chk(label, value, state, why=None, src=None):
        return {"label": label, "value": value,
                "state": state if isinstance(state, str) else ("ok" if state else "bad"),
                "why": why, "src": src or fsrc}

    if fin:
        checks = [
            chk("watertight", "yes" if (fin["boundary_edges"] == 0 and
                                        fin["nonmanifold_edges"] == 0) else "NO",
                fin["boundary_edges"] == 0 and fin["nonmanifold_edges"] == 0,
                "%d boundary (open) edges, %d non-manifold edges. A closed volume is the "
                "one thing a slicer cannot work around, and voxel remesh is the only thing "
                "that produced one - hole filling moved the Euler number by exactly zero."
                % (fin["boundary_edges"], fin["nonmanifold_edges"])),
            chk("one connected shell", fin["islands"], fin["islands"] == 1,
                "the raw candidates carried 4-11 floating fragments; every good one "
                "repaired down to exactly 1"),
            chk("winding consistent, normals outward, is_volume",
                "yes" if (fin["winding"] and fin["is_volume"]) else "NO",
                fin["winding"] and fin["is_volume"]),
            chk("blocking problems", ", ".join(fin["blocking"]) or "none",
                not fin["blocking"],
                "mesh_doctor's own list of things that stop this being a solid"),
            chk("triangles", "{:,}".format(fin["faces"]), "warn",
                "far more than a print needs. It makes a 133 MB STL and some slicers are "
                "slow or unhappy with a file that size. Decimating to a few hundred "
                "thousand faces would almost certainly be fine and was NOT tested."),
            chk("genus", "~%d" % fin["genus"], "warn",
                "a few hundred small tunnels through the solid, from reconstruction noise. "
                "A slicer only needs inside and outside so this should not matter - but it "
                "was not sliced and it was not sectioned to confirm."),
            chk("size at 150 mm", "%s mm, zmin %g" % (
                " x ".join("%.1f" % v for v in fin["size_mm"]), fin["zmin_mm"]), True,
                "%.1f cm3 of solid. STL carries no units, so the export is already in "
                "millimetres and Z-up." % fin["volume_cm3"]),
        ]
    else:
        checks = [
            chk("watertight", "yes" if win.get("fixed_watertight") else "NO",
                bool(win.get("fixed_watertight")), src="mesh/REPORT.json"),
            chk("islands after repair", win.get("fixed_islands"),
                win.get("fixed_islands") == 1, src="mesh/REPORT.json"),
            chk("blocking problems", ", ".join(win.get("fixed_blocking") or []) or "none",
                not (win.get("fixed_blocking") or []), src="mesh/REPORT.json"),
        ]
    thick = []
    if st.get("under_1mm_150") is not None:
        thick.append({"label": "surface under 1.0 mm at a 150 mm print",
                      "value": "%.2f%%" % st["under_1mm_150"],
                      "state": "ok" if st["under_1mm_150"] < 5 else "bad",
                      "why": "against this project's own 5% convention. FDM, 0.4 mm nozzle.",
                      "src": "mesh/VERDICT.md 2"})
    if st.get("under_03mm_150") is not None:
        thick.append({"label": "surface under 0.3 mm at a 150 mm print",
                      "value": "%.2f%%" % st["under_03mm_150"], "state": "ok",
                      "why": "the resin floor. 150 mm is a resin print.",
                      "src": "mesh/VERDICT.md 6"})
    if st.get("p10_150_mm") is not None:
        thick.append({"label": "10th-percentile wall thickness at 150 mm",
                      "value": "%.2f mm" % st["p10_150_mm"], "state": "ok", "why": None,
                      "src": "mesh/VERDICT.md 2"})
    g = fin or {"overhang_frac": win.get("overhang_area_frac"),
                "flat_ceiling_frac": win.get("flat_ceiling_frac"),
                "bed_contact_mm2": win.get("bed_contact_mm2")}
    geom = [
        {"label": "surface past 45 degrees",
         "value": "%.2f%%" % (100 * (g.get("overhang_frac") or 0)), "state": "ok",
         "why": "modest. The outstretched arms and the hair flare are the offenders. "
                "45 degrees is a rule of thumb, not a measurement from a machine.",
         "src": fsrc},
        {"label": "near-horizontal ceilings",
         "value": "%.2f%%" % (100 * (g.get("flat_ceiling_frac") or 0)), "state": "ok",
         "why": None, "src": fsrc},
        {"label": "bed contact", "value": "%.1f mm2" % (g.get("bed_contact_mm2") or 0),
         "state": "bad",
         "why": "bed-contact / height^2 = 0.0089 against the project's 0.015 flag. Her "
                "boots are pointed with a raised heel so she stands on two small "
                "triangles. SHE NEEDS A BASE - and one was since added: mesh_prep.py "
                "rasterises a 50 mm plinth into the same voxel grid, so it is fused by "
                "construction rather than boolean-unioned. That took bed contact to "
                "1,953 mm2 and the ratio to 0.0875. The file with the plinth is "
                "print/TERRA_150mm.stl and it is the one to slice; the numbers in THIS "
                "panel describe the mesh stage, before the base.",
         "src": fsrc},
    ]
    return {"mesh": (fin or {}).get("mesh") or win.get("name"),
            "candidate": win.get("name"),
            "voxel_res": (fin or {}).get("voxel_res"),
            "provenance":
                "Every number in this panel describes the file that was exported - the "
                "voxel-res %s repair. It is NOT the object each candidate card reports: "
                "terra_mesh.py repaired every candidate at mesh_doctor's default "
                "voxel-res 320 so they could be compared under identical treatment, and "
                "that is a different mesh (333k faces against 2.67M). Comparisons between "
                "candidates are fair; their absolute repaired numbers are optimistic."
                % ((fin or {}).get("voxel_res") or "?"),
            "checks": checks, "thickness": thick,
            "geometry": geom,
            "thin_where": [
                {"band": "z 30-45 mm (decile 2)", "thin": "32.2%"},
                {"band": "z 45-60 mm (decile 3)", "thin": "32.3%"},
                {"band": "z 0-15 mm, the boots (decile 0)", "thin": "0.0%"},
                {"band": "z 135-150 mm, the top of the hair (decile 9)", "thin": "1.9%"},
            ],
            "thin_where_note":
                "THE BRIEF PREDICTED THE OPPOSITE. Hunyuan3D reconstructs her hair as fat "
                "fused sausage locks, which are among the THICKEST material in the model. "
                "The thin thing is the skirt fringe at thigh-to-knee height. Do not go "
                "looking for the thin-shell problem at the top of a figure.",
            "height_ladder": [
                {"height_mm": 150, "under_1mm": "6.96%", "p10": "1.19 mm"},
                {"height_mm": 200, "under_1mm": "1.61%", "p10": "1.58 mm"},
                {"height_mm": 250, "under_1mm": "1.18%", "p10": "1.99 mm"},
                {"height_mm": 300, "under_1mm": "0.89%", "p10": "2.36 mm"},
            ],
            "height_ladder_note":
                "Measured on the runner-up D_s512, which is why the 150 mm row differs "
                "from the winner's 1.66%. The jump between 150 and 200 is steep because a "
                "cluster of fringe features sits right at about 1 mm at 150 mm scale.",
            "unverified": [
                "NO SLICER OPENED ANY OF THESE FILES. None is installed on the box. "
                "Watertightness is verified by re-loading the written STL through trimesh; "
                "that PrusaSlicer, Cura or Bambu Studio ingest it cleanly is not verified. "
                "STL is the safer of the two written formats.",
                "NO PRINTER. Every feature-size floor here - FDM 0.8-1.2 mm, resin 0.3 mm, "
                "the 45-degree overhang rule, the material weights - is a rule of thumb "
                "from general practice, not a machine measurement. No printer was ever "
                "identified for this project.",
                "THE 5% under-minimum threshold and the 0.015 bed-contact flag are this "
                "project's own conventions, chosen by the agent who wrote mesh_doctor. "
                "They are not industry standards. Treat a failure as 'stop and look'.",
                "THE SOLID CARRIES GENUS ~329 - a few hundred small tunnels from "
                "reconstruction noise. A slicer only needs inside and outside so this "
                "should not matter, but it was not sliced and it was not sectioned.",
                "THE RENDERS ON THIS PAGE are terra_mesh.py's own orthographic "
                "point-splat rasteriser, not a production renderer. No shadows, no ambient "
                "occlusion, no perspective - it flatters a shape slightly. Silhouette, "
                "surface form and feature legibility are what it was judged on.",
            ]}


def character(cid):
    cid = str(cid or "").strip()
    cards = _cards()
    if cid not in cards:
        # tolerate a lowercase or slug spelling
        hit = next((k for k in cards if k.lower() == cid.lower()), None)
        if not hit:
            return None
        cid = hit
    d = _pipeline_dir(cid)
    if not os.path.isdir(d):
        return {"id": cid, "name": cards[cid].get("name") or cid, "state": "none",
                "root": None, "stages": STAGES, "failures": FAILURES}
    root_url = "/samples/" + os.path.basename(d)
    a = Assets(d, root_url)
    report = _read_json(os.path.join(d, "mesh", "REPORT.json"), {}) or {}
    cands = _candidates(a, d, report)
    out = {
        "id": cid,
        "name": cards[cid].get("name") or cid,
        "state": "printable" if (_listdir(os.path.join(d, "print"), [".stl", ".3mf"])
                                 or _listdir(os.path.join(d, "mesh", "print"),
                                             [".stl", ".3mf"])) else "meshed",
        "root": root_url,
        "rel": os.path.relpath(d, ROOT).replace(os.sep, "/"),
        "stages": STAGES,
        "source": _source(a, d, report),
        "prep": report.get("prep") or {},
        "candidates": cands,
        "splats": _splats(a, d, report),
        "deliverables": _deliverables(a, d),
        "audit": _audit(cands),
        "failures": _failures(a),
        "docs": {
            "verdict": _read_text(os.path.join(d, "mesh", "VERDICT.md")),
            "verdict_rel": os.path.relpath(os.path.join(d, "mesh", "VERDICT.md"),
                                           ROOT).replace(os.sep, "/"),
            "recipe_rel": "craft/CHARACTER_TO_PRINT.md",
            "printing_rel": "craft/PRINTING.md",
        },
        "totals": {
            "candidates": len(cands),
            "failed": len([c for c in cands if c["state"] == "fail"]),
            "assets": a.n,
            "asset_bytes": a.bytes,
        },
        "missing": a.missing,
    }
    return out


def payload(cid=None):
    chars = characters()
    rank = {"printable": 0, "meshed": 1, "sourced": 2, "started": 3, "none": 4}
    done = sorted(chars, key=lambda c: (rank.get(c["state"], 9), c["id"]))
    # The character that got furthest. It is both the default view and the tree the
    # failure gallery's pictures come from - a character nobody has run has no pictures of
    # its own, and the failure modes are properties of the pipeline rather than of her.
    ref = done[0] if done and done[0]["state"] != "none" else None
    if not cid:
        cid = ref["id"] if ref else None
    ref_fail = FAILURES
    if ref:
        rd = _pipeline_dir(ref["id"])
        ref_fail = _failures(Assets(rd, "/samples/" + os.path.basename(rd)))
    return {
        "_": "studio/_tools/model3d_index.py. Numbers are read out of each character's "
             "mesh/REPORT.json, which terra_mesh.py wrote from mesh_doctor.py's JSON. "
             "Nothing is measured here.",
        "generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "characters": chars,
        "character": character(cid) if cid else None,
        "reference": ref["id"] if ref else None,
        "stages": STAGES,
        "failures": ref_fail,
        "recipe": "craft/CHARACTER_TO_PRINT.md",
        # Shipped as text rather than as a link into /docs, so the page renders the recipe
        # whether or not docs.py has been re-run since the file was written. A page that
        # tells you how to do this for the next character is the deliverable; it should not
        # depend on a second tool having been run.
        "recipe_text": _read_text(os.path.join(ROOT, "craft", "CHARACTER_TO_PRINT.md")),
    }


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(
        description="Assemble the /model3d payload from what is on disk. Reads only.")
    ap.add_argument("--character", "-c", help="which character (default: the one that got "
                                              "furthest)")
    ap.add_argument("--json", action="store_true", help="print the whole payload")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any asset a payload names is not on disk")
    a = ap.parse_args()

    p = payload(a.character)
    if a.json:
        print(json.dumps(p, indent=1))
        return 0

    ch = p["character"]
    print("characters with a 3D pipeline on disk:")
    for c in p["characters"]:
        print("  %-9s %-10s %2d candidates  %d print files" %
              (c["id"], c["state"], c["candidates"], c["prints"]))
    if not ch:
        print("\nnothing has been run. craft/CHARACTER_TO_PRINT.md is the recipe.")
        return 0
    if ch.get("state") == "none":
        # Asked for a character with no pipeline. Not an error - the page has a whole view
        # for this case - but there is nothing to summarise, and reaching for ch["totals"]
        # here is what made `--character NIKA` a traceback.
        print("\n%s has no 3D pipeline on disk (studio/samples/%s_3d/ does not exist)."
              % (ch["id"], _slug(ch["id"])))
        print("craft/CHARACTER_TO_PRINT.md is the recipe. Nothing to check.")
        return 0
    print("\n%s - %s, %d candidates (%d failed), %d assets, %.0f MB" % (
        ch["id"], ch["state"], ch["totals"]["candidates"], ch["totals"]["failed"],
        ch["totals"]["assets"], ch["totals"]["asset_bytes"] / 1e6))
    for c in ch["candidates"]:
        print("  %-6s %-16s octree %-4s thr %-5s %10s faces  %s" % (
            c["state"].upper(), c["name"], c.get("octree"), c.get("threshold"),
            "{:,}".format(c.get("raw_faces") or 0),
            "no orbit render" if not c.get("orbit") else ""))
    print("\ndeliverables:")
    for f in ch["deliverables"]:
        print("  %-6s %-32s %7.1f MB" % (f["state"].upper(), f["name"], f["bytes"] / 1e6))
    if ch["missing"]:
        print("\nMISSING (%d):" % len(ch["missing"]))
        for m in ch["missing"]:
            print("  " + m)
    if a.check:
        return 1 if ch["missing"] else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
