#!/usr/bin/env python3
"""studio/_tools/prints_routes.py - the payload behind /prints.

    python3 studio/_tools/prints_routes.py          a human summary
    python3 studio/_tools/prints_routes.py --json   the payload the page reads

WHAT THIS IS. The downloaded 3D-print library: cards in studio/models3d/, meshes in
studio/samples/models3d/<id>/. Separate from /model3d, which is the *generated* mesh
pipeline for a character - different provenance, different question. This page answers
"what can I print", that one answers "did the character survive being turned into a mesh".

IT MEASURES NOTHING. Every number here is read out of the card, which models3d.py wrote
from mesh_doctor.py's own diagnosis. If a number here disagrees with a mesh, the card is
stale - run `models3d.py remeasure`, do not edit this file.

WHY STATE IS READ AND NOT RECOMPUTED. An earlier version of the summary decided readiness
by counting how many notes a model had, which reported a mesh with no real-world scale as
both 'ready to print' and 'needs scaling' in the same table. The card carries an explicit
state; this reads it.
"""
import argparse, glob, json, os, urllib.parse

TOOLS = os.path.dirname(os.path.abspath(__file__))
STUDIO = os.path.dirname(TOOLS)
CARDS = os.path.join(STUDIO, "models3d")
FILES = os.path.join(STUDIO, "samples", "models3d")

# The order a person actually cares about: what can I print right now, what needs one
# step, what is decorative, what do I not know yet.
def _url(rel):
    """A sample URL for a path that may contain spaces and parentheses.

    NASA ships files called `NGC3344 (part 2).stl`. Pasted into href unencoded, the browser
    404s - which showed up as missing thumbnails, but silently broke the DOWNLOAD links
    too. quote() with a safe '/' so separators survive and everything else is escaped.
    """
    return "/samples/models3d/" + urllib.parse.quote(rel, safe="/")


ORDER = {"ready as-is": 0, "printable, needs a step": 1,
         "not printable": 2, "not judged": 3, "unreadable": 4}

STATE_MEANS = {
    "ready as-is": "watertight, sensibly scaled, no warnings - send it to the slicer",
    "printable, needs a step": "a solid mesh, but scale it or split it first",
    "not printable": "not a watertight solid. Most of these are volumetric renders - "
                     "nebulae and galaxies - which are surfaces, not objects. "
                     "mesh_doctor repair can sometimes make one printable",
    "not judged": "measured before mesh_doctor was wired in - run models3d.py remeasure",
    "unreadable": "mesh_doctor could not read or finish diagnosing this mesh",
}


def _thumb(sid):
    """Any image the source shipped alongside the mesh. Several NASA folders include an
    assembly diagram or a render, which is far more use than a generic box icon."""
    d = os.path.join(FILES, sid)
    if not os.path.isdir(d):
        return None
    for dirpath, _, names in os.walk(d):
        for n in sorted(names):
            if n.lower().endswith((".jpg", ".jpeg", ".png")):
                rel = os.path.relpath(os.path.join(dirpath, n), FILES).replace("\\", "/")
                return _url(rel)
    return None


def payload():
    items, states = [], {}
    for p in sorted(glob.glob(os.path.join(CARDS, "*.json"))):
        try:
            c = json.load(open(p, encoding="utf-8"))
        except Exception:
            continue
        m = c.get("measured") or {}
        v = c.get("verdict") or {}
        state = v.get("state") or ("fetched" if c.get("fetched") else "not fetched")
        states[state] = states.get(state, 0) + 1

        meshes = []
        d = os.path.join(FILES, c["id"])
        if os.path.isdir(d):
            for dirpath, _, names in os.walk(d):
                for n in sorted(names):
                    if not n.lower().endswith((".stl", ".obj", ".3mf")):
                        continue
                    fp = os.path.join(dirpath, n)
                    rel = os.path.relpath(fp, FILES).replace("\\", "/")
                    meshes.append({"name": n, "mb": round(os.path.getsize(fp) / 1e6, 1),
                                   "url": _url(rel)})
        items.append({
            "id": c["id"], "name": c.get("name", c["id"]),
            "state": state, "why": v.get("why") or [],
            "mm": m.get("mm"), "faces": m.get("faces"),
            "components": m.get("components"),
            "volume_cm3": m.get("volume_cm3"),
            "needs_scale": v.get("needs_scale"), "oversize": v.get("oversize"),
            "licence": c.get("licence"), "source": c.get("source"),
            "source_url": c.get("source_url"),
            "attribution_required": c.get("attribution_required"),
            "measured_file": c.get("measured_file"),
            "thumb": _thumb(c["id"]),
            "meshes": sorted(meshes, key=lambda f: -f["mb"]),
        })
    items.sort(key=lambda it: (ORDER.get(it["state"], 9), it["name"].lower()))
    return {"items": items, "states": states, "state_means": STATE_MEANS,
            "total": len(items),
            "sources": {"nasa": {"name": "NASA 3D Resources",
                                 "licence": "public domain (US Government work)",
                                 "url": "https://github.com/nasa/NASA-3D-Resources"}}}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()
    d = payload()
    if a.json:
        print(json.dumps(d, indent=1))
        return 0
    print("  %d models" % d["total"])
    for s, n in sorted(d["states"].items(), key=lambda kv: ORDER.get(kv[0], 9)):
        print("    %-26s %3d   %s" % (s, n, STATE_MEANS.get(s, "")[:60]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
